PACKAGE_NAME="omarchy-t2-radio"
PACKAGE_VERSION="1.1"
AUTOINSTALL="yes"
BUILD_EXCLUSIVE_KERNEL="-t2$"
MAKE[0]="bash build-modules.sh ${kernelver}"
BUILT_MODULE_NAME[0]="brcmfmac"
BUILT_MODULE_LOCATION[0]="drivers/net/wireless/broadcom/brcm80211/brcmfmac"
DEST_MODULE_LOCATION[0]="/kernel/drivers/net/wireless/broadcom/brcm80211/brcmfmac"
BUILT_MODULE_NAME[1]="brcmfmac-wcc"
BUILT_MODULE_LOCATION[1]="drivers/net/wireless/broadcom/brcm80211/brcmfmac/wcc"
DEST_MODULE_LOCATION[1]="/kernel/drivers/net/wireless/broadcom/brcm80211/brcmfmac/wcc"
BUILT_MODULE_NAME[2]="brcmfmac-cyw"
BUILT_MODULE_LOCATION[2]="drivers/net/wireless/broadcom/brcm80211/brcmfmac/cyw"
DEST_MODULE_LOCATION[2]="/kernel/drivers/net/wireless/broadcom/brcm80211/brcmfmac/cyw"
BUILT_MODULE_NAME[3]="brcmfmac-bca"
BUILT_MODULE_LOCATION[3]="drivers/net/wireless/broadcom/brcm80211/brcmfmac/bca"
DEST_MODULE_LOCATION[3]="/kernel/drivers/net/wireless/broadcom/brcm80211/brcmfmac/bca"
BUILT_MODULE_NAME[4]="hci_bcm4377"
BUILT_MODULE_LOCATION[4]="drivers/bluetooth"
DEST_MODULE_LOCATION[4]="/kernel/drivers/bluetooth"
