"""Offline source-default policy fixtures; no deployment, EFI or power calls."""
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import tempfile
import unittest

HERE = Path(__file__).resolve().parents[1]
def load(name, path):
  spec = importlib.util.spec_from_file_location(name, path)
  module = importlib.util.module_from_spec(spec)
  spec.loader.exec_module(module)
  return module
P = load("default_policy", HERE / "hibernate/boot_policy.py")
PRODUCT = load("default_product", HERE / "hibernate/product.py")
PAIR = load("default_pair", HERE / "experiments/stage-hibernation-uki-pair.py")
MACHINE = "0123456789abcdef0123456789abcdef"


def region_text(count, tag="a", machine=MACHINE):
  """limine-snapper-sync region as found in the real /+Omarchy entry (5-space indent)."""
  if count == 0: return ""
  text = "     //Snapshots\n     ### Auto-generated by limine-snapper-sync\n     comment: " + str(count) + " snapshots\n"
  for index in range(1, count + 1):
    text += ("     ///" + str(index) + " \u2502 2026-09-17 17:35:4" + str(index) + "\n     comment: 4.0." + str(index) + "-1\n     ////linux-t2\n"
      "     comment: Kernel version: 7.1.8-arch1-Watanare-T2-3-t2\n     comment: kernel-id=linux-t2\n     protocol: efi\n"
      "     path: boot():/" + machine + "/limine_history/omarchy_linux-t2.efi_sha256_" + tag * 64 + "#" + tag * 128 + "\n"
      "     cmdline: root=/dev/mapper/root rootflags=subvol=/@/.snapshots/" + str(index) + "/snapshot\n")
  return text + "\n"


def os_entry(production, count=0, tag="a", machine=MACHINE):
  """Real structure: OS entry, kernel entry, blank, snapshot region, then the EFI fallback entry."""
  return ("/+Omarchy\n### This OS entry is auto-generated by limine-entry-tool\ncomment: Omarchy\ncomment: machine-id=" + machine + " order-priority=50 \n"
    "  //linux-t2\n  ### This kernel entry is auto-generated by limine-entry-tool\n  comment: kernel-id=linux-t2 \n  protocol: efi\n  "
    + production + "  cmdline: root=/dev/mapper/root rw\n\n" + region_text(count, tag, machine)
    + "/EFI fallback\nprotocol: efi\npath: boot():/EFI/BOOT/BOOTX64.EFI\n")


class Policy(unittest.TestCase):
  snapshots = None  # None: the historical flat fixture; a number: real OS-entry layout with that many snapshot entries

  def setUp(self):
    self.temp = tempfile.TemporaryDirectory()
    self.addCleanup(self.temp.cleanup)
    self.root = Path(self.temp.name) / "root"
    self.root.mkdir(mode=0o700)
    images = {}
    for role in ("source", "restore"):
      raw = role.encode()
      images[role] = {"entry_id": PAIR.entry_id(role, P.digest(raw)), "sha256": P.digest(raw),
                      "blake2": hashlib.blake2b(raw).hexdigest(), "provenance_sha256": "f" * 64}
      self.write(PAIR.IMAGES[role], raw)
    self.write("boot/EFI/Linux/omarchy_linux-t2.efi", b"production")
    production_path = "path: boot():/EFI/Linux/omarchy_linux-t2.efi#" + hashlib.blake2b(b"production").hexdigest() + "\n"
    if self.snapshots is not None: production_path = os_entry(production_path, self.snapshots)
    original = ("default_entry: 2\n" + production_path).encode()
    self.write(PAIR.BACKUP, original)
    before = "timeout: 3\ndefault_entry: 2\n" + production_path + PAIR.BEGIN + "\n"
    for role in images:
      before += "/" + images[role]["entry_id"] + "\npath: boot():/EFI/Linux/" + PAIR.IMAGES[role].name + "#" + images[role]["blake2"] + "\n"
    self.before = (before + PAIR.END + "\n").encode()
    self.receipt = {"kernel_policy": "production-linux-unchanged", "images": images,
      "original_limine_sha256": P.digest(original), "staged_limine_sha256": P.digest(self.before),
      "production_uki_sha256": P.digest(b"production")}
    self.raw = json.dumps(self.receipt).encode()
    self.write(P.RECEIPT, self.raw)
    self.write(P.LIMINE, self.before)
    self.write(PAIR.SINGLE.ENTRIES, b"\x06\0\0\0" + ("\0".join(item["entry_id"] for item in images.values()) + "\0").encode("utf-16-le"))
    self.proposal = P.prepare(self.before, self.raw)
    self.policy = {**self.proposal["policy"], "approved": True}
    self.config = {"staged_receipt_sha256": P.digest(self.raw)}
    self.report = {"manifest": {role + "_sha256": images[role]["sha256"] for role in images},
      "audited_details": {"production_uki_sha256": P.digest(b"production"), "provenance_sha256": {role: "f" * 64 for role in images}}}

  def write(self, relative, raw):
    path = self.root / relative
    path.parent.mkdir(parents=True, exist_ok=True)
    for directory in (path.parent, *path.parent.parents):
      if directory == self.root.parent: break
      directory.chmod(0o700)
    path.write_bytes(raw)
    path.chmod(0o600)
    return path

  def activate_fixture(self):
    self.write(P.POLICY, json.dumps(self.policy).encode())
    self.write(P.BACKUP, self.before)
    self.write(P.LIMINE, self.proposal["after"])

  def test_prepare_is_pure_unapproved_exact_single_line_change(self):
    self.assertFalse(self.proposal["policy"]["approved"])
    self.assertFalse(self.proposal["physical_permission"])
    self.assertEqual((self.root / P.LIMINE).read_bytes(), self.before)
    self.assertEqual((self.root / P.RECEIPT).read_bytes(), self.raw)
    self.assertEqual(P.normalize_source_default(self.proposal["after"], self.receipt), self.before)
    with self.assertRaises(ValueError): P.validate(self.proposal["policy"], self.before, self.proposal["after"], self.raw)

  def test_comments_before_active_line_are_preserved(self):
    comment = ("#default_entry: 2\n#default_entry: " + self.policy["source_entry_id"] + "\n").encode()
    before = comment + self.before
    raw = json.dumps({**self.receipt, "staged_limine_sha256": P.digest(before)}).encode()
    proposal = P.prepare(before, raw)
    self.assertTrue(proposal["after"].startswith(comment))
    self.assertEqual(P.normalize_source_default(proposal["after"], json.loads(raw)), before)

  def test_absent_policy_stock_strict_and_product_only_overlay(self):
    self.assertFalse(P.verify(self.root, P.digest(self.raw)))
    PRODUCT.verify_deployment(self.root, self.config, self.report)
    self.activate_fixture()
    self.assertTrue(P.verify(self.root, P.digest(self.raw)))
    PRODUCT.verify_deployment(self.root, self.config, self.report)
    with self.assertRaises(ValueError): PRODUCT.TRIAL.verify_deployment(self.root, self.config, self.report)
    with self.assertRaises(ValueError): PAIR.verify_staged(self.root, self.receipt)
    self.assertEqual((self.root / P.RECEIPT).read_bytes(), self.raw)

  def test_live_product_rejects_a_replaced_or_historical_deployment_callback(self):
    # The check rejects callbacks before reading live files or acquiring locks.
    for callback in (PRODUCT.TRIAL.verify_deployment, lambda *args: None):
      with self.assertRaisesRegex(ValueError, "No injected live"):
        PRODUCT.check({}, None, {}, ledger=None, archive_directory=None, root="/", deployment_check=callback)

  def test_full_checks_still_reject_image_production_originalbackup_and_efi_changes(self):
    self.activate_fixture()
    paths = (PAIR.IMAGES["source"], PAIR.IMAGES["restore"], Path("boot/EFI/Linux/omarchy_linux-t2.efi"), PAIR.BACKUP)
    for relative in paths:
      with self.subTest(relative=relative):
        path = self.root / relative
        original = path.read_bytes()
        path.write_bytes(original + b"changed")
        with self.assertRaises(ValueError): PRODUCT.verify_deployment(self.root, self.config, self.report)
        path.write_bytes(original)
    self.write(PAIR.SINGLE.DEFAULT, b"persistent EFI default")
    with self.assertRaises(ValueError): PRODUCT.verify_deployment(self.root, self.config, self.report)

  def test_every_foreign_default_duplicate_case_and_unrelated_byte_rejected(self):
    line = ("default_entry: " + self.policy["source_entry_id"] + "\n").encode()
    alternatives = (b"default_entry: 9\n", b"default_entry: 2\n", b"default_entry: foreign\n",
      ("default_entry: " + self.receipt["images"]["restore"]["entry_id"] + "\n").encode(),
      line.replace(b"default_entry", b"Default_Entry"), b" " + line, line + b"default_entry: 2\n")
    for alternative in alternatives:
      with self.assertRaises(ValueError): P.normalize_source_default(self.proposal["after"].replace(line, alternative), self.receipt)
    for actual in (self.proposal["after"] + b"#changed\n", self.proposal["after"].replace(b"timeout: 3", b"timeout: 0")):
      with self.assertRaises(ValueError): P.validate(self.policy, self.before, actual, self.raw)
    for key in (b"DEFAULT_ENTRY: 2\n", b"default_entry: 2\r\n", b"default_entry: 2\nremember_last_entry: yes\n"):
      before = self.before.replace(b"default_entry: 2\n", key)
      receipt = {**self.receipt, "staged_limine_sha256": P.digest(before)}
      with self.assertRaises(ValueError): P.prepare(before, json.dumps(receipt).encode())

  def test_policy_pins_approval_unknown_fields_and_receipt_drift_rejected(self):
    for change in ({"approved": 1}, {"approved": False}, {"staged_receipt_sha256": "0" * 64},
      {"before_limine_sha256": "0" * 64}, {"after_limine_sha256": "0" * 64}, {"source_entry_id": "restore"}, {"extra": True}):
      with self.assertRaises(ValueError): P.validate({**self.policy, **change}, self.before, self.proposal["after"], self.raw)
    with self.assertRaises(ValueError): P.validate(self.policy, self.before, self.proposal["after"], self.raw + b" ")

  def test_private_backup_missing_symlink_writable_or_linked_evidence_rejected(self):
    self.activate_fixture()
    for relative in (P.POLICY, P.BACKUP, P.RECEIPT, P.LIMINE):
      with self.subTest(relative=relative):
        path = self.root / relative
        original = path.read_bytes()
        path.chmod(0o666)
        with self.assertRaises(ValueError): P.verify(self.root, P.digest(self.raw))
        path.chmod(0o600)
        linked = path.with_name(path.name + ".linked")
        os.link(path, linked)
        with self.assertRaises(ValueError): P.verify(self.root, P.digest(self.raw))
        linked.unlink()
        target = path.with_name(path.name + ".retained")
        path.rename(target)
        path.symlink_to(target.name)
        with self.assertRaises((ValueError, OSError)): P.verify(self.root, P.digest(self.raw))
        path.unlink()
        target.rename(path)
    (self.root / P.BACKUP).unlink()
    with self.assertRaises(FileNotFoundError): P.verify(self.root, P.digest(self.raw))

  def test_symlinked_directory_noncanonical_root_and_duplicate_json_fail(self):
    self.activate_fixture()
    with self.assertRaises(ValueError): P.verify(self.root / "..", P.digest(self.raw))
    state = self.root / P.STATE
    retained = state.with_name("retained-state")
    state.rename(retained)
    state.symlink_to(retained.name)
    with self.assertRaises(ValueError): P.verify(self.root, P.digest(self.raw))
    state.unlink()
    retained.rename(state)
    (self.root / P.POLICY).write_bytes(b'{"approved":true,"approved":false}')
    with self.assertRaises(ValueError): P.verify(self.root, P.digest(self.raw))

  def test_fifo_evidence_reads_are_nonblocking_and_fail_closed(self):
    self.activate_fixture()
    for relative in (P.POLICY, P.BACKUP, P.RECEIPT, P.LIMINE):
      path = self.root / relative
      original = path.read_bytes()
      path.unlink()
      os.mkfifo(path, mode=0o600)
      with self.assertRaises(ValueError): P.verify(self.root, P.digest(self.raw))
      path.unlink()
      self.write(relative, original)


PRODUCTION = "path: boot():/EFI/Linux/omarchy_linux-t2.efi#" + "b" * 128 + "\n"


class Canonical(unittest.TestCase):
  def entry(self, count=1, tag="a"): return os_entry(PRODUCTION, count, tag).encode()

  def test_region_removal_is_exact_for_zero_one_and_three_snapshots(self):
    for count in (0, 1, 3):
      raw = self.entry(count)
      self.assertEqual(P.limine_canonical(raw), self.entry(0))
      self.assertEqual((P.snapshot_region(raw) is None), count == 0)
    self.assertEqual(P.limine_canonical(self.entry(3)), self.entry(0).replace(b"\n\n/EFI", b"\n\n/EFI"))
    self.assertEqual(len(self.entry(3)) - len(region_text(3).encode()), len(P.limine_canonical(self.entry(3))))

  def test_churn_reorder_and_removal_are_blind_but_nothing_else(self):
    base = P.limine_canonical(self.entry(3))
    self.assertEqual(P.limine_canonical(self.entry(5, "c")), base)
    reordered = self.entry(3).decode().replace("     ///1", "     ///9").replace("     ///3", "     ///1").encode()
    self.assertEqual(P.limine_canonical(reordered), base)
    for change in ((b"path: boot():/EFI/Linux/omarchy_linux-t2.efi#" + b"b" * 128, b"path: boot():/EFI/Linux/omarchy_linux-t2.efi#" + b"c" * 128),
                   (b"root=/dev/mapper/root rw", b"root=/dev/mapper/root rw evil"), (b"/EFI fallback", b"/EFI fallbacK"),
                   (b"comment: Omarchy\n", b"comment: Omarch\n")):
      self.assertNotEqual(P.limine_canonical(self.entry(3).replace(*change)), base)

  def test_with_region_splices_recorded_region_including_insertion_and_removal(self):
    for recorded in (0, 1, 3):
      for current in (0, 2, 5):
        spliced = P.with_region(self.entry(current, "d"), self.entry(recorded, "a"))
        self.assertEqual(spliced, self.entry(recorded, "a"))

  def test_malformed_or_misplaced_regions_fail_closed(self):
    good = self.entry(1).decode()
    region = region_text(1)
    bad = {
      "header only": good.replace("     ### Auto-generated by limine-snapper-sync\n", ""),
      "wrong indent": good.replace("     //Snapshots", "    //Snapshots"),
      "other generator": good.replace("limine-snapper-sync", "limine-snapper-syncx", 1).replace("     //Snapshots\n     ### Auto-generated by limine-snapper-syncx", "     //Snapshots\n     ### Auto-generated by other"),
      "second region": good.replace("/EFI fallback", region + "/EFI fallback"),
      "default inside": good.replace("     comment: 1 snapshots\n", "     comment: 1 snapshots\n     default_entry: 1\n"),
      "remember inside": good.replace("     comment: 1 snapshots\n", "     comment: 1 snapshots\n     remember_last_entry: yes\n"),
      "foreign path": good.replace("limine_history", "limine_historyx/../../EFI"),
      "other machine": good.replace("boot():/" + MACHINE + "/limine_history", "boot():/" + "1" * 32 + "/limine_history"),
      "esp path": good.replace("boot():/" + MACHINE + "/limine_history/", "boot():/EFI/Linux/"),
      "smuggled entry": good.replace("/EFI fallback", "     /Evil\n     protocol: efi\n/EFI fallback"),
      "smuggled kernel": good.replace("/EFI fallback", "  //linux-t2\n  protocol: efi\n/EFI fallback"),
      "smuggled option": good.replace("/EFI fallback", "timeout: 0\n/EFI fallback"),
      "path before entry": good.replace("     comment: 1 snapshots\n", "     comment: 1 snapshots\n     path: boot():/" + MACHINE + "/limine_history/x\n"),
      "protocol other": good.replace("     protocol: efi\n     path: boot():/" + MACHINE, "     protocol: linux\n     path: boot():/" + MACHINE),
      "carriage return": good.replace("     comment: 1 snapshots\n", "     comment: 1 snapshots\r\n"),
      "sync text elsewhere": good.replace("comment: Omarchy\n", "comment: limine-snapper-sync\n", 1),
      "no machine id": good.replace("machine-id=" + MACHINE, "machine-id=none"),
    }
    for name, text in bad.items():
      with self.subTest(name), self.assertRaises(ValueError): P.limine_canonical(text.encode())

  def test_region_outside_the_omarchy_entry_or_before_the_kernel_is_refused(self):
    region = region_text(1)
    good = self.entry(0).decode()
    outside = good.replace("/EFI fallback\n", "/EFI fallback\n" + region)  # inside the fallback entry
    before_kernel = good.replace("  //linux-t2\n", region + "  //linux-t2\n")
    top_level = region + good
    for name, text in {"fallback entry": outside, "before kernel": before_kernel, "top level": top_level}.items():
      with self.subTest(name), self.assertRaises(ValueError): P.limine_canonical(text.encode())
    with self.assertRaises(ValueError): P.limine_canonical(region.encode() + b"x" * (P.MAX_BYTES))


class Snapshots(Policy):
  """The whole policy suite again on the real OS-entry layout, plus snapshot churn."""
  snapshots = 3

  def churn(self, raw, count, tag="c"):
    return raw.replace(region_text(self.snapshots).encode(), region_text(count, tag).encode())

  def test_source_default_verification_admits_snapshot_churn(self):
    self.activate_fixture()
    for count in (0, 1, 3, 6):
      self.write(P.LIMINE, self.churn(self.proposal["after"], count))
      self.assertTrue(P.verify(self.root, P.digest(self.raw)))
      PRODUCT.verify_deployment(self.root, self.config, self.report)
      PAIR.verify_staged(self.root, self.receipt, source_default=True)

  def test_stock_pair_verification_admits_snapshot_churn(self):
    for count in (0, 1, 3, 6):
      self.write(P.LIMINE, self.churn(self.before, count))
      PAIR.verify_staged(self.root, self.receipt)
      PRODUCT.verify_deployment(self.root, self.config, self.report)

  def test_churn_never_masks_any_other_change(self):
    self.activate_fixture()
    active = self.proposal["after"]
    entry = self.policy["source_entry_id"]
    changes = ((("default_entry: " + entry).encode(), b"default_entry: 2"), (b"timeout: 3", b"timeout: 4"),
      (b"omarchy_linux-t2.efi#", b"omarchy_linux-t2.efi#0"), (b"root=/dev/mapper/root rw\n", b"root=/dev/mapper/root rw x\n"),
      (b"/EFI fallback", b"/EFI fallbacK"), (b"BOOTX64.EFI", b"BOOTX65.EFI"), (PAIR.BEGIN.encode(), b"# BEGIN other"),
      (b"mba_t2_hibernation_source.efi#", b"mba_t2_hibernation_source.efi#0"))
    for old, new in changes:
      for count in (3, 1):
        with self.subTest(old=old, count=count):
          changed = self.churn(active, count).replace(old, new, 1)
          self.assertNotEqual(changed, self.churn(active, count))
          self.write(P.LIMINE, changed)
          with self.assertRaises(ValueError): P.verify(self.root, P.digest(self.raw))
          with self.assertRaises(ValueError): PAIR.verify_staged(self.root, self.receipt, source_default=True)

  def test_stock_mode_refuses_default_pair_and_kernel_changes_under_churn(self):
    for old, new in ((b"default_entry: 2", b"default_entry: 3"), (PAIR.END.encode(), b"# END other"),
                     (b"omarchy_linux-t2.efi#", b"omarchy_linux-t2.efi#0"), (b"/EFI fallback", b"/EFI fallbacK")):
      with self.subTest(old=old):
        self.write(P.LIMINE, self.churn(self.before, 1).replace(old, new, 1))
        with self.assertRaises(ValueError): PAIR.verify_staged(self.root, self.receipt)

  def test_malformed_region_in_current_bytes_refuses_hibernation(self):
    self.activate_fixture()
    self.write(P.LIMINE, self.proposal["after"].replace(b"     ////linux-t2", b"     default_entry: 1\n     ////linux-t2", 1))
    with self.assertRaises(ValueError): P.verify(self.root, P.digest(self.raw))
    self.write(P.LIMINE, self.proposal["after"].replace(b"limine_history", b"elsewhere", 1))
    with self.assertRaises(ValueError): P.verify(self.root, P.digest(self.raw))

  def test_deactivation_validation_accepts_churn_and_still_binds_the_rest(self):
    churned = self.churn(self.proposal["after"], 2)
    P.validate(self.policy, self.before, churned, self.raw)
    P.validate(self.policy, self.before, self.churn(self.proposal["after"], 0), self.raw)
    with self.assertRaises(ValueError): P.validate(self.policy, self.before, churned.replace(b"timeout: 3", b"timeout: 4"), self.raw)
    with self.assertRaises(ValueError): P.validate(self.policy, self.before, self.churn(self.before, 2), self.raw)
    self.assertEqual(P.normalize_source_default(churned, self.receipt, donor=self.before), self.before)
    with self.assertRaises(ValueError): P.normalize_source_default(churned, self.receipt)


if __name__ == "__main__": unittest.main()
