"""Offline fixtures for retiring a staged hibernation pair after a production kernel update."""
import fcntl
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import tempfile
import unittest

HERE = Path(__file__).resolve().parents[1]


def load(name, path):
  spec = importlib.util.spec_from_file_location(name, path)
  module = importlib.util.module_from_spec(spec)
  spec.loader.exec_module(module)
  return module


PAIR = load("retire_pair", HERE / "experiments/stage-hibernation-uki-pair.py")
MACHINE = "0123456789abcdef0123456789abcdef"
STEPS = ("archive", "journal", "limine", "image-source", "image-restore", "backup", "receipt", "record")


def sha(data):
  return hashlib.sha256(data).hexdigest()


def b2(data):
  return hashlib.blake2b(data).hexdigest()


def efi_string(value):
  return b"\x07\x00\x00\x00" + (value + "\x00").encode("utf-16-le")


def region(count, tag):
  if count == 0:
    return ""
  text = "     //Snapshots\n     ### Auto-generated by limine-snapper-sync\n     comment: " + str(count) + " snapshots\n"
  for index in range(1, count + 1):
    text += (
      "     ///" + str(index) + " │ 2026-09-17 17:35:4" + str(index) + "\n     comment: 4.0." + str(index) + "-1\n     ////linux-t2\n"
      "     comment: kernel-id=linux-t2\n     protocol: efi\n"
      "     path: boot():/" + MACHINE + "/limine_history/omarchy_linux-t2.efi_sha256_" + tag * 64 + "#" + tag * 128 + "\n"
      "     cmdline: root=/dev/mapper/root rootflags=subvol=/@/.snapshots/" + str(index) + "/snapshot\n"
    )
  return text + "\n"


def limine_text(production, count, tag):
  return (
    "timeout: 3\ndefault_entry: 2\n"
    "/+Omarchy\n### This OS entry is auto-generated by limine-entry-tool\ncomment: Omarchy\n"
    "comment: machine-id=" + MACHINE + " order-priority=50 \n"
    "  //linux-t2\n  protocol: efi\n  path: boot():/EFI/Linux/omarchy_linux-t2.efi#" + b2(production) + "\n"
    "  cmdline: root=/dev/mapper/root rw\n\n" + region(count, tag)
    + "/EFI fallback\nprotocol: efi\npath: boot():/EFI/BOOT/BOOTX64.EFI\n"
  )


class Retire(unittest.TestCase):
  def setUp(self):
    self.temp = tempfile.TemporaryDirectory()
    self.addCleanup(self.temp.cleanup)
    self.root = Path(self.temp.name) / "root"
    self.old_production = b"production kernel 7.2.6"
    self.new_production = b"production kernel 7.2.7"
    self.path("boot/EFI/Linux/omarchy_linux-t2.efi").parent.mkdir(parents=True)
    self.path("boot/EFI/Linux/omarchy_linux-t2.efi").write_bytes(self.old_production)
    self.original = limine_text(self.old_production, 2, "a").encode()
    self.images = {}
    for role in PAIR.IMAGES:
      data = (role + " uki").encode()
      self.images[role] = {
        "entry_id": PAIR.entry_id(role, sha(data)), "sha256": sha(data), "blake2": b2(data),
        "provenance_sha256": "f" * 64, "experiment_id": "x-" + role, "data": data,
      }
      self.write(PAIR.IMAGES[role], data)
    self.block = PAIR.stage_block(self.images)
    self.staged = self.original + self.block
    self.write(PAIR.SINGLE.LIMINE, self.staged)
    self.write(PAIR.BACKUP, self.original)
    self.receipt = {
      "state": "staged", "kernel_policy": "production-linux-unchanged",
      "production_uki_sha256": sha(self.old_production),
      "original_limine_sha256": sha(self.original), "staged_limine_sha256": sha(self.staged),
      "images": {role: {k: v for k, v in self.images[role].items() if k != "data"} for role in PAIR.IMAGES},
    }
    self.write(PAIR.RECEIPT, json.dumps(self.receipt, indent=2, sort_keys=True).encode() + b"\n")
    self.receipt_raw = self.path(PAIR.RECEIPT).read_bytes()
    evidence = self.path(PAIR.STATE / "s4-vectors")
    evidence.mkdir()
    (evidence / "guard").write_text("consumed")
    self.write(PAIR.SINGLE.SELECTED, efi_string("Omarchy.linux-t2"))
    self.write(PAIR.MAINTENANCE, b"{}")
    self.write(PAIR.PHYSICAL_LOCK, b"")
    self.path(PAIR.PHYSICAL_LOCK).chmod(0o600)
    self.path(PAIR.DB_LOCK).parent.mkdir(parents=True, exist_ok=True)
    self.updated_limine = None

  def path(self, relative):
    return self.root / relative

  def write(self, relative, data):
    path = self.path(relative)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(data)

  def kernel_update(self):
    """What limine-mkinitcpio and limine-snapper-sync do: new UKI, new hash line, new snapshots."""
    self.write("boot/EFI/Linux/omarchy_linux-t2.efi", self.new_production)
    self.updated_limine = limine_text(self.new_production, 4, "c").encode()
    self.write(PAIR.SINGLE.LIMINE, self.updated_limine + self.block)

  def retire(self, **arguments):
    return PAIR.retire(self.root, **arguments)

  def refuses(self, expected, action=None, foreign_db_lock=False):
    before = self.snapshot()
    with self.assertRaises(ValueError) as context:
      (action or self.retire)()
    self.assertIn(expected, str(context.exception))
    self.assertEqual(self.snapshot(), before, "refusal must not change anything")
    self.assertEqual(self.path(PAIR.DB_LOCK).exists(), foreign_db_lock)

  def snapshot(self):
    return {
      str(path.relative_to(self.root)): (path.read_bytes() if path.is_file() else None)
      for path in sorted(self.root.rglob("*")) if path.is_file() or path.is_dir()
    }

  def assert_retired(self):
    self.assertEqual(self.path(PAIR.SINGLE.LIMINE).read_bytes(), self.updated_limine)
    self.assertEqual(self.path("boot/EFI/Linux/omarchy_linux-t2.efi").read_bytes(), self.new_production)
    for role in PAIR.IMAGES:
      self.assertFalse(self.path(PAIR.IMAGES[role]).exists())
    self.assertFalse(self.path(PAIR.RECEIPT).exists())
    self.assertFalse(self.path(PAIR.BACKUP).exists())
    self.assertEqual((self.path(PAIR.STATE / "s4-vectors") / "guard").read_text(), "consumed")
    self.assertFalse(self.path(PAIR.DB_LOCK).exists())

  def test_happy_path_archives_then_removes_only_our_entries(self):
    self.kernel_update()
    result = self.retire()
    self.assertEqual(result["state"], "retired")
    self.assert_retired()
    record = result["retirement"]
    self.assertEqual(record["retired_receipt_sha256"], sha(self.receipt_raw))
    self.assertEqual(record["old_production_uki_sha256"], sha(self.old_production))
    self.assertEqual(record["new_production_uki_sha256"], sha(self.new_production))
    archive = self.path(PAIR.ARCHIVE_ROOT) / record["archive"]
    self.assertEqual(oct(archive.stat().st_mode & 0o777), "0o700")
    self.assertEqual(oct(archive.parent.stat().st_mode & 0o777), "0o700")
    manifest = json.loads((archive / "manifest.json").read_text())
    self.assertEqual(set(manifest["files"]), {
      "receipt.json", "limine.conf.before", "limine.conf.at-retirement", "images/source.efi", "images/restore.efi",
    })
    for name, digest in manifest["files"].items():
      self.assertEqual(sha((archive / name).read_bytes()), digest)
    self.assertEqual((archive / "images/source.efi").read_bytes(), self.images["source"]["data"])
    self.assertEqual((archive / "limine.conf.before").read_bytes(), self.original)
    self.assertEqual((archive / "receipt.json").read_bytes(), self.receipt_raw)
    self.assertEqual(sha((archive / "limine.conf.at-retirement").read_bytes()), record["limine_before_sha256"])
    self.assertEqual(oct((archive / "receipt.json").stat().st_mode & 0o777), "0o600")

  def test_dry_run_prints_plan_and_changes_nothing(self):
    self.kernel_update()
    before = self.snapshot()
    plan = self.retire(dry_run=True)
    self.assertEqual(plan["state"], "dry-run")
    self.assertEqual(plan["steps"], list(STEPS))
    self.assertEqual(plan["new_production_uki_sha256"], sha(self.new_production))
    self.assertTrue(plan["limine_block_present"])
    self.assertEqual(self.snapshot(), before)

  def test_rerun_after_success_is_a_noop_report(self):
    self.kernel_update()
    first = self.retire()
    before = self.snapshot()
    again = self.retire()
    self.assertEqual(again["state"], "already-retired")
    self.assertEqual(again["retirement"], first["retirement"])
    self.assertEqual(self.snapshot(), before)
    # Even once maintenance is over, the report needs no preconditions.
    self.path(PAIR.MAINTENANCE).unlink()
    self.assertEqual(self.retire()["state"], "already-retired")

  def test_never_retired_without_receipt_is_an_error(self):
    self.path(PAIR.RECEIPT).unlink()
    self.refuses("receipt is missing")

  def test_crash_at_every_step_then_rerun_completes(self):
    for step in STEPS[:-1]:
      with self.subTest(step=step):
        self.tearDown_fixture()
        self.setUp()
        self.kernel_update()

        def hook(name, step=step):
          if name == step:
            raise RuntimeError("injected crash after " + step)

        with self.assertRaises(RuntimeError):
          self.retire(step_hook=hook)
        self.assertFalse(self.path(PAIR.DB_LOCK).exists(), "locks are released on crash")
        result = self.retire()
        self.assertEqual(result["state"], "retired")
        self.assert_retired()
        self.assertEqual(self.retire()["state"], "already-retired")

  def tearDown_fixture(self):
    self.temp.cleanup()

  def test_crash_after_record_is_complete(self):
    self.kernel_update()

    def hook(name):
      if name == "record":
        raise RuntimeError("late crash")

    with self.assertRaises(RuntimeError):
      self.retire(step_hook=hook)
    self.assertEqual(self.retire()["state"], "already-retired")
    self.assert_retired()

  def test_every_durable_write_can_fail_and_rerun_completes(self):
    writer = PAIR.atomic_write
    self.tearDown_fixture()
    calls = 0
    for fail_at in range(1, 30):
      self.setUp()
      self.kernel_update()
      counter = [0]

      def failing(path, data, mode, fail_at=fail_at, counter=counter):
        counter[0] += 1
        if counter[0] == fail_at:
          raise RuntimeError("injected write failure")
        writer(path, data, mode)

      PAIR.atomic_write = failing
      try:
        try:
          self.retire()
          finished = True
        except RuntimeError:
          finished = False
      finally:
        PAIR.atomic_write = writer
      if finished:
        calls = fail_at
        self.assert_retired()
        break
      self.assertEqual(self.retire()["state"], "retired", fail_at)
      self.assert_retired()
      self.tearDown_fixture()
    self.assertGreater(calls, 5, "the sweep must cover the archive writes")

  def test_interrupted_retirement_can_be_rolled_back_and_retired_again(self):
    for step in STEPS[1:-1]:
      with self.subTest(step=step):
        self.tearDown_fixture()
        self.setUp()
        self.kernel_update()
        before = self.snapshot()

        def hook(name, step=step):
          if name == step:
            raise RuntimeError("injected crash")

        with self.assertRaises(RuntimeError):
          self.retire(step_hook=hook)
        self.assertEqual(PAIR.retire_rollback(self.root)["state"], "retirement-rolled-back")
        after = self.snapshot()
        for name, data in before.items():
          self.assertEqual(after.get(name), data, name)
        self.assertEqual(len(PAIR.incomplete_journals(self.root)), 0)
        self.assertEqual(self.retire()["state"], "retired")
        self.assert_retired()

  def test_rollback_without_interrupted_retirement_refuses(self):
    self.kernel_update()
    self.refuses("incomplete retirement journal", lambda: PAIR.retire_rollback(self.root))
    self.retire()
    self.refuses("incomplete retirement journal", lambda: PAIR.retire_rollback(self.root))

  def test_production_unchanged_refuses_and_points_at_rollback(self):
    self.refuses("Production UKI is unchanged; use rollback")

  def test_image_mismatch_refuses(self):
    self.kernel_update()
    self.write(PAIR.IMAGES["restore"], b"foreign restore")
    self.refuses("restore image does not match")

  def test_missing_image_refuses(self):
    self.kernel_update()
    self.path(PAIR.IMAGES["source"]).unlink()
    self.refuses("image is missing")

  def test_armed_transactions_refuse(self):
    self.kernel_update()
    for relative in (PAIR.SINGLE.ONESHOT, PAIR.SINGLE.DEFAULT):
      self.write(relative, efi_string("MBA-T2-hibernation-source-x"))
      self.refuses("armed")
      self.path(relative).unlink()
    self.write(PAIR.SINGLE.SELECTED, efi_string(self.receipt["images"]["source"]["entry_id"]))
    self.refuses("stock boot")
    self.path(PAIR.SINGLE.SELECTED).unlink()
    self.refuses("LoaderEntrySelected is absent")

  def test_pending_trial_refuses(self):
    self.kernel_update()
    self.write(PAIR.TRIAL_STATE / "cycle/.pending-1234", b"x")
    self.refuses("trial is pending")

  def test_not_in_maintenance_refuses(self):
    self.kernel_update()
    self.path(PAIR.MAINTENANCE).unlink()
    self.refuses("only allowed during package maintenance")

  def test_active_product_refuses(self):
    self.kernel_update()
    for relative in (
      "etc/omarchy/t2-hibernate-product.enabled", PAIR.PRODUCT_STATE / "boot-policy.json",
      PAIR.PRODUCT_STATE / "source-default-activation.pending", PAIR.PRODUCT_STATE / "source-default-deactivation.pending",
      PAIR.PRODUCT_STATE / "runtime-upgrade.pending",
    ):
      self.write(relative, b"")
      self.refuses("active or transitioning")
      self.path(relative).unlink()

  def test_foreign_limine_drift_refuses(self):
    self.kernel_update()
    updated = self.path(PAIR.SINGLE.LIMINE).read_bytes()
    drifts = {
      "timeout": lambda raw: raw.replace(b"timeout: 3", b"timeout: 9"),
      "default": lambda raw: raw.replace(b"default_entry: 2", b"default_entry: 1"),
      "cmdline": lambda raw: raw.replace(b"cmdline: root=/dev/mapper/root rw", b"cmdline: root=/dev/mapper/root rw quiet"),
      "foreign entry": lambda raw: raw.replace(b"/EFI fallback", b"/Foreign\nprotocol: efi\npath: boot():/x.efi\n/EFI fallback"),
      "fallback": lambda raw: raw.replace(b"BOOTX64.EFI", b"OTHER.EFI"),
      "trailing": lambda raw: raw + b"# trailing\n",
    }
    for name, drift in drifts.items():
      with self.subTest(name):
        self.write(PAIR.SINGLE.LIMINE, drift(updated))
        self.refuses("Limine changed beyond")
    self.write(PAIR.SINGLE.LIMINE, updated)
    self.assertEqual(self.retire()["state"], "retired")

  def test_unrecognised_snapshot_text_and_modified_block_refuse(self):
    self.kernel_update()
    updated = self.path(PAIR.SINGLE.LIMINE).read_bytes()
    self.write(PAIR.SINGLE.LIMINE, updated.replace(b"     comment: 4 snapshots\n", b"     comment: 4 snapshots\n     surprise: yes\n"))
    self.refuses("snapshot region")
    self.write(PAIR.SINGLE.LIMINE, updated.replace(b"comment: One-shot T2 hibernation source", b"comment: edited"))
    self.refuses("pair text")
    self.write(PAIR.SINGLE.LIMINE, updated + self.block)
    self.refuses("duplicated")

  def test_stale_production_hash_refuses(self):
    self.write("boot/EFI/Linux/omarchy_linux-t2.efi", self.new_production)
    self.refuses("not coherent with the current production UKI")

  def test_backup_tamper_refuses(self):
    self.kernel_update()
    self.write(PAIR.BACKUP, self.original + b"#")
    self.refuses("backup changed")

  def test_unknown_state_files_and_bad_receipt_state_refuse(self):
    self.kernel_update()
    self.write(PAIR.STATE / "stray", b"x")
    self.refuses("unknown files")
    self.path(PAIR.STATE / "stray").unlink()
    for state in ("rolling-back", "preparing"):
      receipt = dict(self.receipt, state=state)
      self.write(PAIR.RECEIPT, json.dumps(receipt).encode())
      self.refuses("cannot be retired")

  def test_held_locks_refuse(self):
    self.kernel_update()
    self.write(PAIR.DB_LOCK, b"")
    self.refuses("db.lck is held", foreign_db_lock=True)
    self.path(PAIR.DB_LOCK).unlink()
    descriptor = os.open(self.path(PAIR.PHYSICAL_LOCK), os.O_RDONLY)
    try:
      fcntl.flock(descriptor, fcntl.LOCK_EX)
      self.refuses("physical lock")
    finally:
      os.close(descriptor)
    self.assertEqual(self.retire()["state"], "retired")

  def test_rolled_back_receipt_with_changed_production_retires_without_images(self):
    self.assertEqual(PAIR.rollback(self.root)["state"], "rolled-back")
    self.assertEqual(self.path(PAIR.SINGLE.LIMINE).read_bytes(), self.original)
    self.write("boot/EFI/Linux/omarchy_linux-t2.efi", self.new_production)
    self.updated_limine = limine_text(self.new_production, 4, "c").encode()
    self.write(PAIR.SINGLE.LIMINE, self.updated_limine)
    plan = self.retire(dry_run=True)
    self.assertFalse(plan["limine_block_present"])
    self.assertEqual(self.retire()["retirement"]["receipt_state"], "rolled-back")
    self.assert_retired()

  def test_retire_does_not_change_production_or_other_state(self):
    self.kernel_update()
    self.write("boot/EFI/Linux/other.efi", b"other")
    self.write(PAIR.STATE / "test-resume-vectors/v", b"vector")
    self.retire()
    self.assertEqual(self.path("boot/EFI/Linux/other.efi").read_bytes(), b"other")
    self.assertEqual(self.path(PAIR.STATE / "test-resume-vectors/v").read_bytes(), b"vector")

  def test_second_retirement_of_identical_receipt_gets_its_own_archive(self):
    self.kernel_update()
    first = self.retire()["retirement"]
    for role in PAIR.IMAGES:
      self.write(PAIR.IMAGES[role], self.images[role]["data"])
    self.write(PAIR.BACKUP, self.original)
    self.write(PAIR.RECEIPT, self.receipt_raw)
    self.write(PAIR.SINGLE.LIMINE, self.updated_limine + self.block)
    second = self.retire()["retirement"]
    self.assertNotEqual(first["archive"], second["archive"])
    self.assertTrue(first["archive"].endswith("-0") and second["archive"].endswith("-1"))
    self.assert_retired()


if __name__ == "__main__":
  unittest.main()
