#!/usr/bin/python3
"""Exercise the single-image upstream-model stager against a fake ESP, Limine, efivars and product state."""

import hashlib
import importlib.util
import json
import os
from pathlib import Path
import subprocess
import tempfile


script = Path(__file__).resolve().parents[1] / "upstream-model/stage-upstream-model.py"
spec = importlib.util.spec_from_file_location("upstream_model_stage", script)
stage = importlib.util.module_from_spec(spec)
spec.loader.exec_module(stage)
C = stage.C

MACHINE = "0123456789abcdef0123456789abcdef"
BOOT_A = "11111111-2222-3333-4444-555555555555"
BOOT_B = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"
BOOT_C = "99999999-8888-7777-6666-555555555555"


def sha(data):
  return hashlib.sha256(data).hexdigest()


def efi_string(value):
  return b"\x07\x00\x00\x00" + (value + "\x00").encode("utf-16-le")


def efi_strings(values):
  return b"\x06\x00\x00\x00" + "".join(value + "\x00" for value in values).encode("utf-16-le")


def rejects(action, expected):
  try:
    action()
  except (ValueError, RuntimeError) as error:
    assert expected in str(error), error
  else:
    raise AssertionError("Unsafe action accepted: " + expected)


def objcopy(*arguments):
  subprocess.run(("objcopy", *map(str, arguments)), check=True, capture_output=True)


def region_text(count, tag="a"):
  if count == 0:
    return ""
  text = "     //Snapshots\n     ### Auto-generated by limine-snapper-sync\n     comment: " + str(count) + " snapshots\n"
  for index in range(1, count + 1):
    text += ("     ///" + str(index) + " │ 2026-09-17 17:35:4" + str(index) + "\n     comment: 4.0." + str(index) + "-1\n     ////linux-t2\n"
             "     comment: Kernel version: 7.2.7-test\n     comment: kernel-id=linux-t2\n     protocol: efi\n"
             "     path: boot():/" + MACHINE + "/limine_history/omarchy_linux-t2.efi_sha256_" + tag * 64 + "#" + tag * 128 + "\n"
             "     cmdline: root=/dev/mapper/root rootflags=subvol=/@/.snapshots/" + str(index) + "/snapshot\n")
  return text + "\n"


def limine_text(production_blake2, snapshots=1, tag="a", pair_block=True):
  text = (
    "timeout: 3\ndefault_entry: 2\n"
    "/+Omarchy\n### This OS entry is auto-generated by limine-entry-tool\ncomment: Omarchy\ncomment: machine-id=" + MACHINE + " order-priority=50 \n"
    "  //linux-t2\n  ### This kernel entry is auto-generated by limine-entry-tool\n  comment: kernel-id=linux-t2 \n  protocol: efi\n"
    "  path: boot():/EFI/Linux/omarchy_linux-t2.efi#" + production_blake2 + "\n  cmdline: root=/dev/mapper/root rw\n\n"
    + region_text(snapshots, tag) +
    "/EFI fallback\nprotocol: efi\npath: boot():/EFI/BOOT/BOOTX64.EFI\n"
  )
  if pair_block:
    text += "\n# BEGIN omarchy T2 hibernation pair\n/MBA-T2-hibernation-source-0000000000000000\nprotocol: efi\npath: boot():/EFI/Linux/mba_t2_hibernation_source.efi#" + "0" * 128 + "\n# END omarchy T2 hibernation pair\n"
  return text


def make_build(directory, production, *, mutate=None):
  directory.mkdir(mode=0o700)
  initrd = directory / C.BUILD_INITRD
  initrd.write_bytes(b"upstream model initramfs")
  image = directory / C.BUILD_IMAGE
  objcopy("--update-section=.initrd=" + str(initrd), production, image)
  data = image.read_bytes()
  provenance = {
    "candidate": C.CANDIDATE, "protocol": C.PROTOCOL, "experiment_id": "upstream-test",
    "candidate_uki_sha256": sha(data), "production_uki_sha256": sha(production.read_bytes()),
    "unchanged_production_sections_sha256": {".linux": sha(b"k"), ".cmdline": sha(b"c")},
    "modified_sections_sha256": None,
    "deltas": {"D1_modules_added": ["t2bce_audio"], "D2_initramfs_blacklist": list(C.BLACKLISTED_MODULES), "build_hook": C.HOOK},
    "initrd_manifest_diff": {"added": [], "removed": [], "changed": []},
    "modules": {name: {"sha256": sha(name.encode()), "srcversion": "SRC" + name} for name in C.T2BCE_MODULES},
    "production_modified": False, "installed": False, "boot_entry_created": False, "hardware_qualified": False,
  }
  if mutate is not None:
    mutate(provenance, image)
    provenance["candidate_uki_sha256"] = provenance.get("candidate_uki_sha256") or sha(image.read_bytes())
  (directory / C.BUILD_PROVENANCE).write_text(json.dumps(provenance))
  for path in (image, initrd, directory / C.BUILD_PROVENANCE):
    path.chmod(0o600)
  return directory


def fixture(base, *, maintenance=True, build=True):
  root = base / "root"
  production = root / "boot/EFI/Linux/omarchy_linux-t2.efi"
  production.parent.mkdir(parents=True)
  kernel, cmdline = base / "kernel", base / "cmdline"
  kernel.write_bytes(b"healthy production kernel")
  cmdline.write_bytes(b"root=/dev/mapper/root resume=/dev/mapper/root\x00")
  objcopy("--add-section=.linux=" + str(kernel), "--add-section=.cmdline=" + str(cmdline),
          "--add-section=.initrd=" + str(kernel), "/usr/lib/systemd/boot/efi/linuxx64.efi.stub", production)
  limine = root / stage.LIMINE
  original = limine_text(hashlib.blake2b(production.read_bytes()).hexdigest())
  limine.write_text(original)
  selected = root / stage.SELECTED
  selected.parent.mkdir(parents=True)
  selected.write_bytes(efi_string(C.STOCK_ENTRY))
  boot = root / stage.BOOT_ID
  boot.parent.mkdir(parents=True)
  boot.write_text(BOOT_A + "\n")
  if maintenance:
    marker = root / stage.MAINTENANCE
    marker.parent.mkdir(parents=True)
    marker.write_text("pending\n")
  pair = root / stage.PAIR_STATE
  pair.mkdir(parents=True)
  (pair / "receipt.json").write_text(json.dumps({"images": {"source": {"sha256": "5" * 64}}}))
  (root / "sys/firmware/efi/efivars").mkdir(parents=True, exist_ok=True)
  built = make_build(base / "build", production) if build else None
  return root, built, limine, original, production


def bootctl_for(root, log=None):
  def bootctl(arguments, check):
    assert arguments[:2] == ["bootctl", "set-oneshot"] and check
    oneshot = root / stage.ONESHOT
    if log is not None:
      log.append(arguments[2])
    if arguments[2]:
      oneshot.write_bytes(efi_string(arguments[2]))
    else:
      oneshot.unlink()
  return bootctl


def advertise(root, receipt):
  (root / stage.ENTRIES).write_bytes(efi_strings((C.STOCK_ENTRY, receipt["entry_id"])))


def set_boot(root, selected, boot_id):
  (root / stage.SELECTED).write_bytes(efi_string(selected))
  (root / stage.BOOT_ID).write_text(boot_id + "\n")


def tree_state(root):
  result = {}
  for relative in (stage.PAIR_STATE, stage.PRODUCT_STATE):
    for path in sorted((root / relative).rglob("*")) if (root / relative).exists() else []:
      result[str(path)] = path.read_bytes() if path.is_file() else None
  return result


with tempfile.TemporaryDirectory(prefix="t2-upstream-stage-refusals-") as temporary:
  base = Path(temporary)

  root, build, limine, original, production = fixture(base / "no-maintenance", maintenance=False)
  rejects(lambda: stage.stage(root, build), "not in package maintenance")
  assert limine.read_text() == original and not (root / stage.C.STATE).exists()

  for name in ("boot-policy.json", "source-default-activation.pending", "runtime-upgrade.pending"):
    root, build, limine, original, production = fixture(base / ("active-" + name))
    (root / stage.PRODUCT_STATE / name).write_text("x")
    rejects(lambda: stage.stage(root, build), "not inactive")
  root, build, limine, original, production = fixture(base / "opt-in")
  (root / "etc/omarchy").mkdir(parents=True)
  (root / "etc/omarchy/t2-hibernate-product.enabled").write_text("")
  rejects(lambda: stage.stage(root, build), "not inactive")

  root, build, limine, original, production = fixture(base / "symlink-marker")
  (root / stage.MAINTENANCE).unlink()
  (root / stage.MAINTENANCE).symlink_to("elsewhere")
  rejects(lambda: stage.stage(root, build), "Refusing symlink")

  root, build, limine, original, production = fixture(base / "default")
  (root / stage.DEFAULT).write_bytes(efi_string("x"))
  rejects(lambda: stage.stage(root, build), "ersistent EFI default")

  root, build, limine, original, production = fixture(base / "oneshot")
  (root / stage.ONESHOT).write_bytes(efi_string("x"))
  rejects(lambda: stage.stage(root, build), "already armed")

  root, build, limine, original, production = fixture(base / "not-stock")
  set_boot(root, "Something.else", BOOT_A)
  rejects(lambda: stage.stage(root, build), "not the healthy stock")

  root, build, limine, original, production = fixture(base / "rejected-static")
  assert "974246c01bdc329917651b35f5dbe0b80e2f5e4125987f7c0050e20e4fc39ffd" in stage.rejected_hashes(root)
  rejects(lambda: stage.reject_image(root, "974246c01bdc329917651b35f5dbe0b80e2f5e4125987f7c0050e20e4fc39ffd"), "rejected, consumed or terminal")
  original_hashes = stage.rejected_hashes
  stage.rejected_hashes = lambda _root: {sha((build / C.BUILD_IMAGE).read_bytes())}
  try:
    rejects(lambda: stage.stage(root, build), "rejected, consumed or terminal")
  finally:
    stage.rejected_hashes = original_hashes
  assert not (root / stage.ESP_IMAGE).exists()

  # Pair tooling evidence is read but never written; its hashes are refused.
  root, build, limine, original, production = fixture(base / "pair-evidence")
  data = (build / C.BUILD_IMAGE).read_bytes()
  (root / stage.PAIR_STATE / "receipt.json").write_text(json.dumps({"images": {"restore": {"sha256": sha(data)}}}))
  rejects(lambda: stage.stage(root, build), "rejected, consumed or terminal")
  (root / stage.PAIR_STATE / "receipt.json").write_text("{}")
  (root / stage.PAIR_STATE / "s4-vectors").mkdir()
  (root / stage.PAIR_STATE / "s4-vectors" / sha(data)).mkdir()
  rejects(lambda: stage.stage(root, build), "rejected, consumed or terminal")

  for section in (".linux", ".cmdline"):
    root, build, limine, original, production = fixture(base / ("section" + section))
    replacement = base / ("replacement" + section)
    replacement.write_bytes(b"different physical boot section")
    image = build / C.BUILD_IMAGE
    changed = base / ("changed" + section + ".efi")
    objcopy("--update-section=" + section + "=" + str(replacement), image, changed)
    changed.replace(image)
    image.chmod(0o600)
    report = json.loads((build / C.BUILD_PROVENANCE).read_text())
    report["candidate_uki_sha256"] = sha(image.read_bytes())
    (build / C.BUILD_PROVENANCE).write_text(json.dumps(report))
    rejects(lambda: stage.stage(root, build), section + " differs from production")
    assert limine.read_text() == original and not (root / stage.ESP_IMAGE).exists()

  def mutate_case(name, expected, change):
    root, build, limine, original, production = fixture(base / name)
    report = json.loads((build / C.BUILD_PROVENANCE).read_text())
    change(report)
    (build / C.BUILD_PROVENANCE).write_text(json.dumps(report))
    rejects(lambda: stage.stage(root, build), expected)
    assert limine.read_text() == original and not (root / stage.ESP_IMAGE).exists()

  mutate_case("replaced-kernel", "replaces the production kernel", lambda r: r.update(modified_sections_sha256={".linux": "c" * 64}))
  mutate_case("wrong-deltas", "declared upstream-model deltas", lambda r: r["deltas"].update(D1_modules_added=[]))
  mutate_case("removed-files", "removes production files", lambda r: r["initrd_manifest_diff"].update(removed=["init"]))
  mutate_case("missing-module", "exactly the four t2bce", lambda r: r["modules"].pop("t2bce_audio"))
  mutate_case("modified-flag", "offline-only", lambda r: r.update(installed=True))
  mutate_case("wrong-protocol", "Unexpected upstream-model provenance", lambda r: r.update(protocol="other"))
  mutate_case("stale-production", "differs from the image build base", lambda r: r.update(production_uki_sha256="d" * 64))

  root, build, limine, original, production = fixture(base / "group-readable")
  (build / C.BUILD_IMAGE).chmod(0o644)
  rejects(lambda: stage.stage(root, build), "private")

  root, build, limine, original, production = fixture(base / "stale-limine")
  limine.write_text(original.replace("#" + hashlib.blake2b(production.read_bytes()).hexdigest(), "#" + "e" * 128))
  rejects(lambda: stage.stage(root, build), "stale or ambiguous")

  root, build, limine, original, production = fixture(base / "unowned")
  limine.write_text(original + "\n/MBA-T2-upstream-model-deadbeefdeadbeef\nprotocol: efi\n")
  rejects(lambda: stage.stage(root, build), "unowned upstream-model entry")

  root, build, limine, original, production = fixture(base / "bad-snapshot")
  limine.write_text(original.replace("     ////linux-t2\n", "     ////linux-t2\n     default_entry: 1\n", 1))
  rejects(lambda: stage.stage(root, build), "")


with tempfile.TemporaryDirectory(prefix="t2-upstream-stage-flow-") as temporary:
  base = Path(temporary)
  root, build, limine, original, production = fixture(base / "flow")
  before_tree = tree_state(root)
  receipt = stage.stage(root, build)
  assert tree_state(root) == before_tree, "staging must not touch pair or product state"
  assert receipt["state"] == "staged" and receipt["entry_id"] == C.ENTRY_PREFIX + receipt["image_sha256"][:16]
  text = limine.read_text()
  assert text.startswith(original) and text.count(C.BEGIN) == 1 and text.count(C.END) == 1
  assert text.count("default_entry: 2") == 1 and "LoaderEntry" not in text
  assert ("path: boot():/EFI/Linux/" + C.ESP_IMAGE + "#" + hashlib.blake2b((build / C.BUILD_IMAGE).read_bytes()).hexdigest()) in text
  assert (root / stage.ESP_IMAGE).read_bytes() == (build / C.BUILD_IMAGE).read_bytes()
  assert (root / stage.ESP_IMAGE).stat().st_mode & 0o777 == 0o600
  assert (root / C.RECEIPT).stat().st_mode & 0o777 == 0o600
  stage.verify_staged(root, receipt)
  rejects(lambda: stage.stage(root, build), "already exists")

  # Evidence directories are preserved and validated.
  for name in C.STATE_NAMES:
    (root / C.STATE / name).mkdir(exist_ok=True)
  (root / C.STATE / "unexpected").write_text("x")
  rejects(lambda: stage.clear_rolled_back(root), "unknown files")
  (root / C.STATE / "unexpected").unlink()

  # Tampering is detected by every later action.
  good = limine.read_bytes()
  limine.write_bytes(good.replace(b"#" + receipt["image_blake2"].encode(), b"#" + b"f" * 128))
  rejects(lambda: stage.verify_staged(root, receipt), "unowned or modified")
  limine.write_bytes(good + b"timeout: 0\n")
  rejects(lambda: stage.verify_staged(root, receipt), "beyond the snapshot region")
  limine.write_bytes(good.replace(b"default_entry: 2", b"default_entry: 3"))
  rejects(lambda: stage.verify_staged(root, receipt), "not exactly entry 2")
  limine.write_bytes(good)
  (root / stage.ESP_IMAGE).write_bytes(b"swapped")
  rejects(lambda: stage.verify_staged(root, receipt), "image changed")
  (root / stage.ESP_IMAGE).write_bytes((build / C.BUILD_IMAGE).read_bytes())
  (root / stage.DEFAULT).write_bytes(efi_string("x"))
  rejects(lambda: stage.verify_staged(root, receipt), "ersistent EFI default")
  (root / stage.DEFAULT).unlink()
  production.write_bytes(production.read_bytes() + b"x")
  rejects(lambda: stage.verify_staged(root, receipt), "stale or ambiguous")
  production.write_bytes(production.read_bytes()[:-1])
  stage.verify_staged(root, receipt)

  # Snapshot churn is tolerated by verification.
  churned = good.replace(region_text(1).encode(), region_text(3, "c").encode())
  assert churned != good
  limine.write_bytes(churned)
  stage.verify_staged(root, receipt)
  limine.write_bytes(good)

  # First arm, from stock: needs advertisement.
  rejects(lambda: stage.arm(root, runner=bootctl_for(root)), "not advertised")
  advertise(root, receipt)
  calls, synced = [], []
  armed = stage.arm(root, runner=bootctl_for(root, calls), sync=lambda: synced.append(True))
  assert armed["state"] == "armed" and calls == [receipt["entry_id"]] and synced
  assert stage.SINGLE.read_efi_string(root / stage.ONESHOT) == receipt["entry_id"]
  assert armed["armed_from_boot_id"] == BOOT_A
  rejects(lambda: stage.arm(root, runner=bootctl_for(root)), "already present")
  rejects(lambda: stage.rollback(root), "Disarm")
  rejects(lambda: stage.clear_rolled_back(root), "Disarm")
  rejects(lambda: stage.mark_booted(root), "was not consumed")
  rejects(lambda: stage.arm_s4(root, 1, runner=bootctl_for(root)), "cannot be armed for S4")

  # Unknown one-shot is never cleared.
  (root / stage.ONESHOT).write_bytes(efi_string("Unrelated"))
  rejects(lambda: stage.disarm(root, runner=bootctl_for(root)), "unknown one-shot")
  (root / stage.ONESHOT).write_bytes(efi_string(receipt["entry_id"]))
  # Disarm is idempotent and leaves a re-armable state.
  assert stage.disarm(root, runner=bootctl_for(root))["state"] == "disarmed"
  assert stage.disarm(root, runner=bootctl_for(root))["state"] == "disarmed"
  assert not (root / stage.ONESHOT).exists()
  stage.arm(root, runner=bootctl_for(root))

  # The one-shot is consumed by a new boot of the exact entry.
  (root / stage.ONESHOT).unlink()
  rejects(lambda: stage.mark_booted(root), "not the exact upstream-model entry")
  set_boot(root, receipt["entry_id"], BOOT_A)
  rejects(lambda: stage.mark_booted(root), "new boot")
  set_boot(root, receipt["entry_id"], BOOT_B)
  booted = stage.mark_booted(root)
  assert booted["state"] == "booted" and booted["test_boot_id"] == BOOT_B

  # S4 arming is only from the test boot, in order, and per cycle.
  rejects(lambda: stage.arm(root, runner=bootctl_for(root)), "healthy stock boot")
  rejects(lambda: stage.arm_s4(root, 0, runner=bootctl_for(root)), "1, 2 or 3")
  rejects(lambda: stage.arm_s4(root, 2, runner=bootctl_for(root)), "out of order")
  set_boot(root, receipt["entry_id"], BOOT_C)
  rejects(lambda: stage.arm_s4(root, 1, runner=bootctl_for(root)), "boot that verified")
  set_boot(root, C.STOCK_ENTRY, BOOT_B)
  rejects(lambda: stage.arm_s4(root, 1, runner=bootctl_for(root)), "exact upstream-model test boot")
  set_boot(root, receipt["entry_id"], BOOT_B)
  one = stage.arm_s4(root, 1, runner=bootctl_for(root))
  assert one["state"] == "s4-armed" and one["last_armed_cycle"] == 1
  assert stage.SINGLE.read_efi_string(root / stage.ONESHOT) == receipt["entry_id"]
  rejects(lambda: stage.arm_s4(root, 2, runner=bootctl_for(root)), "cannot be armed for S4")
  # S4 consumed the one-shot and the same boot returned.
  (root / stage.ONESHOT).unlink()
  assert stage.mark_booted(root)["state"] == "booted"
  set_boot(root, receipt["entry_id"], BOOT_C)
  (root / stage.ONESHOT).write_bytes(efi_string(receipt["entry_id"]))
  (root / stage.ONESHOT).unlink()
  set_boot(root, receipt["entry_id"], BOOT_B)
  two = stage.arm_s4(root, 2, runner=bootctl_for(root))
  assert two["last_armed_cycle"] == 2
  # A refused hibernate write lets the runner disarm and retry; the runner's guards decide whether a cycle was attempted.
  assert stage.disarm(root, runner=bootctl_for(root))["state"] == "disarmed"
  rejects(lambda: stage.arm_s4(root, 4, runner=bootctl_for(root)), "1, 2 or 3")
  assert stage.arm_s4(root, 2, runner=bootctl_for(root))["last_armed_cycle"] == 2
  stage.disarm(root, runner=bootctl_for(root))
  assert stage.arm_s4(root, 3, runner=bootctl_for(root))["last_armed_cycle"] == 3
  stage.disarm(root, runner=bootctl_for(root))
  rejects(lambda: stage.arm_s4(root, 4, runner=bootctl_for(root)), "1, 2 or 3")

  # A terminal image hash cannot be armed again and stays terminal.
  assert stage.mark_terminal(root, receipt["image_sha256"], "S4 cycle failed")
  assert not stage.mark_terminal(root, receipt["image_sha256"], "again")
  rejects(lambda: stage.arm_s4(root, 3, runner=bootctl_for(root)), "rejected, consumed or terminal")
  set_boot(root, C.STOCK_ENTRY, BOOT_C)
  rejects(lambda: stage.arm(root, runner=bootctl_for(root)), "rejected, consumed or terminal")

  # Rollback from the stock boot removes exactly the owned block, preserving snapshot churn.
  limine.write_bytes(churned)
  rolled = stage.rollback(root)
  assert rolled["state"] == "rolled-back"
  assert not (root / stage.ESP_IMAGE).exists()
  assert limine.read_bytes() == churned.replace(stage.entry_block(receipt), b"")
  assert stage.POLICY.limine_canonical(limine.read_bytes()) == stage.POLICY.limine_canonical(original.encode())
  assert C.BEGIN not in limine.read_text()
  assert stage.rollback(root)["state"] == "rolled-back"
  cleared = stage.clear_rolled_back(root)
  assert cleared["state"] == "cleared" and not (root / C.RECEIPT).exists() and not (root / C.BACKUP).exists()
  assert (root / C.TERMINAL / (receipt["image_sha256"] + ".json")).exists() and (root / C.ATTEMPTS).is_dir()
  assert stage.clear_rolled_back(root)["state"] == "cleared"
  assert tree_state(root) == before_tree
  # A terminal hash is never staged again.
  rejects(lambda: stage.stage(root, build), "rejected, consumed or terminal")


with tempfile.TemporaryDirectory(prefix="t2-upstream-stage-crash-") as temporary:
  base = Path(temporary)

  # Crash after the image was written and before Limine was updated: automatic recovery.
  root, build, limine, original, production = fixture(base / "stage-crash")
  real_write = stage.atomic_write

  def failing_limine(path, data, mode):
    if path.name == "limine.conf":
      raise OSError("simulated power loss before Limine update")
    real_write(path, data, mode)

  stage.atomic_write = failing_limine
  try:
    try:
      stage.stage(root, build)
    except OSError as error:
      assert "simulated" in str(error)
    else:
      raise AssertionError("failed staging accepted")
  finally:
    stage.atomic_write = real_write
  assert limine.read_text() == original and not (root / stage.ESP_IMAGE).exists()
  failed = stage.load_receipt(root)
  assert failed["state"] == "stage-failed-recovered"
  rejects(lambda: stage.stage(root, build), "already exists")
  assert stage.rollback(root)["state"] == "rolled-back"
  assert stage.clear_rolled_back(root)["state"] == "cleared"
  assert stage.stage(root, build)["state"] == "staged"

  # Crash while writing the receipt itself, before any ESP change: the unpublished backup is cleaned.
  root, build, limine, original, production = fixture(base / "receipt-crash")

  def failing_receipt(path, data, mode):
    if path.name == "receipt.json":
      raise OSError("simulated receipt failure")
    real_write(path, data, mode)

  stage.atomic_write = failing_receipt
  try:
    try:
      stage.stage(root, build)
    except OSError:
      pass
    else:
      raise AssertionError("failed receipt accepted")
  finally:
    stage.atomic_write = real_write
  assert not (root / C.BACKUP).exists() and not (root / stage.ESP_IMAGE).exists() and limine.read_text() == original

  # Crash between the two arm writes: the arming state still disarms.
  root, build, limine, original, production = fixture(base / "arm-crash")
  receipt = stage.stage(root, build)
  advertise(root, receipt)

  def dying_bootctl(arguments, check):
    (root / stage.ONESHOT).write_bytes(efi_string(arguments[2]))
    raise KeyboardInterrupt

  try:
    stage.arm(root, runner=dying_bootctl)
  except KeyboardInterrupt:
    pass
  assert stage.load_receipt(root)["state"] == "arming"
  rejects(lambda: stage.arm(root, runner=bootctl_for(root)), "cannot be armed from state arming")
  assert stage.disarm(root, runner=bootctl_for(root))["state"] == "disarmed"
  assert not (root / stage.ONESHOT).exists()
  # Crash before the one-shot was written is also recoverable.
  stage.arm(root, runner=bootctl_for(root))
  assert stage.load_receipt(root)["state"] == "armed"
  (root / stage.ONESHOT).unlink()

  # Rollback resumes after a crash between block removal and image removal.
  real_remove_image = stage.remove_image

  def failing_image(root_argument, receipt_argument):
    raise OSError("simulated crash before image removal")

  stage.remove_image = failing_image
  try:
    try:
      stage.rollback(root)
    except OSError:
      pass
    else:
      raise AssertionError("failed rollback accepted")
  finally:
    stage.remove_image = real_remove_image
  assert stage.load_receipt(root)["state"] == "rolling-back"
  assert C.BEGIN not in limine.read_text() and (root / stage.ESP_IMAGE).exists()
  assert stage.rollback(root)["state"] == "rolled-back"
  assert not (root / stage.ESP_IMAGE).exists()
  assert limine.read_text() == original

  # Rollback refuses an unknown image and an unknown Limine text; it never guesses.
  root, build, limine, original, production = fixture(base / "rollback-unknown")
  receipt = stage.stage(root, build)
  (root / stage.ESP_IMAGE).write_bytes(b"foreign")
  rejects(lambda: stage.rollback(root), "unknown upstream-model image")
  (root / stage.ESP_IMAGE).write_bytes((build / C.BUILD_IMAGE).read_bytes())
  limine.write_text(limine.read_text() + "timeout: 0\n")
  rejects(lambda: stage.rollback(root), "beyond the snapshot region")
  assert stage.load_receipt(root)["state"] == "rolling-back"

  # Rollback and clear need the stock boot.
  root, build, limine, original, production = fixture(base / "rollback-boot")
  receipt = stage.stage(root, build)
  set_boot(root, receipt["entry_id"], BOOT_B)
  rejects(lambda: stage.rollback(root), "stock boot")
  set_boot(root, C.STOCK_ENTRY, BOOT_B)
  stage.rollback(root)
  set_boot(root, receipt["entry_id"], BOOT_B)
  rejects(lambda: stage.clear_rolled_back(root), "stock boot")

  # Clear refuses an un-rolled-back transaction.
  root, build, limine, original, production = fixture(base / "clear-early")
  stage.stage(root, build)
  rejects(lambda: stage.clear_rolled_back(root), "rolled back before clearing")

  # Arming refuses once maintenance ends (product reactivated), and a missing kernel policy.
  root, build, limine, original, production = fixture(base / "arm-active")
  receipt = stage.stage(root, build)
  advertise(root, receipt)
  (root / stage.MAINTENANCE).unlink()
  rejects(lambda: stage.arm(root, runner=bootctl_for(root)), "not in package maintenance")
  (root / stage.MAINTENANCE).write_text("pending\n")
  receipt.pop("kernel_policy")
  stage.save_receipt(root, receipt)
  rejects(lambda: stage.arm(root, runner=bootctl_for(root)), "production-kernel boot policy")
  assert not (root / stage.ONESHOT).exists()

print("PASS: upstream-model stager refuses unsafe state and stages, arms, disarms, rolls back and clears idempotently")
