"""Disposable filesystem/lock fixtures only; no live root or power calls."""
import fcntl
import hashlib
import importlib.util
import json
import os
from pathlib import Path
import stat
import unittest
import uuid
from unittest.mock import patch

HERE = Path(__file__).resolve().parents[1]
def load(name, filename):
  spec = importlib.util.spec_from_file_location(name, filename)
  module = importlib.util.module_from_spec(spec)
  spec.loader.exec_module(module)
  return module
T = load("transition", HERE / "hibernate/boot_policy_transition.py")
SLEEP = load("transition_sleep_entry", HERE / "hibernate/sleep_entry.py")
RESUME = {"device": "/dev/mapper/root", "devnum": "254:0", "offset": 7}
F = load("policy_fixture", Path(__file__).with_name("test-hibernate-boot-policy.py"))


MACHINE = "0123456789abcdef0123456789abcdef"


def snapshot_block(numbers, reverse=False):
  """A limine-snapper-sync style //Snapshots sub-tree nested under the Omarchy OS entry."""
  lines = ["", "     //Snapshots", "     ### Auto-generated by limine-snapper-sync", "     comment: %d snapshots" % len(numbers)]
  for number in (reversed(numbers) if reverse else numbers):
    lines += ["     ///%d \u2502 2026-09-%02d 17:35:47" % (number, number), "     comment: 4.0.2-1", "     ////linux-t2",
              "     comment: Kernel version: 7.1.8-test", "     comment: kernel-id=linux-t2", "     protocol: efi",
              "     path: boot():/" + MACHINE + "/limine_history/omarchy_linux-t2.efi_sha256_%s#%s" % (("%02x" % number) * 32, ("%02x" % number) * 64),
              "     cmdline: root=/dev/mapper/root rootflags=subvol=/@/.snapshots/%d/snapshot rw" % number]
  return "\n".join(lines) + "\n"


def with_snapshots(raw, numbers, reverse=False):
  """Replace any existing snapshot sub-tree with the given one, ahead of the staged pair block."""
  text, marker = raw.decode(), "# BEGIN omarchy T2 hibernation pair"
  if "\n     //Snapshots" in text: text = text[:text.index("\n     //Snapshots")] + "\n" + text[text.index(marker):]
  index = text.index(marker)
  if not numbers: return text.encode()
  return (text[:index].rstrip("\n") + "\n" + snapshot_block(numbers, reverse) + text[index:]).encode()


class Transitions(unittest.TestCase):
  def setUp(self):
    self.f = F.Policy("test_prepare_is_pure_unapproved_exact_single_line_change")
    self.f.setUp()
    self.addCleanup(self.f.doCleanups)
    self.root = self.f.root
    self.f.before = self.f.before.replace(b"path: boot():/EFI/Linux/omarchy_linux-t2.efi#", b"/+Omarchy\ncomment: machine-id=" + MACHINE.encode() + b" order-priority=50 \n  //linux-t2\n  protocol: efi\npath: boot():/EFI/Linux/omarchy_linux-t2.efi#", 1)
    # Real files keep a blank line between the OS entry and what follows; the snapshot region is inserted after it.
    self.f.before = self.f.before.replace(b"# BEGIN omarchy T2 hibernation pair", b"\n# BEGIN omarchy T2 hibernation pair", 1)
    self.f.receipt["staged_limine_sha256"] = T.P.digest(self.f.before)
    self.f.raw = json.dumps(self.f.receipt).encode()
    self.f.config["staged_receipt_sha256"] = T.P.digest(self.f.raw)
    self.f.proposal = T.P.prepare(self.f.before, self.f.raw)
    self.f.policy = {**self.f.proposal["policy"], "approved": True}
    self.f.write(T.P.RECEIPT, self.f.raw)
    self.f.write(T.P.LIMINE, self.f.before)
    self.f.write(T.REVIEW, json.dumps(self.f.policy).encode())
    self.f.write(T.OPT_IN, b"").chmod(0o644)
    self.f.write(T.PHYSICAL_LOCK, b"")
    (self.root / T.DB_LOCK).parent.mkdir(parents=True)
    ledger = T.PRODUCT.TX.Ledger(self.root / T.P.STATE / "ledger")
    with ledger._lock(): pass
    source = self.root.parent / "snapshot-source"
    for tree in T.D.TREES: (source / tree).mkdir(parents=True)
    (source / T.D.ENTRYPOINT).write_text("# reviewed fixture; never executed\n")
    (source / T.D.TREES[1] / "fixture.py").write_text("# retained fixture code\n")
    hook = (HERE / "hibernate/00-omarchy-t2-hibernate-guard.hook").read_bytes()
    (source / T.D.UPDATE_GUARD_HOOK).write_bytes(hook)
    (source / T.D.TREES[0] / "update_guard.py").write_bytes((HERE / "hibernate/update_guard.py").read_bytes())
    review = {"protocol": T.D.SCHEMA, "approved": True, "reviewed_commit": "a" * 40, "files": T.D.inventory(source)}
    self.f.write(T.P.STATE / "runtime-deployment-review.json", json.dumps(review).encode())
    T.D.deploy_snapshot(source, root=self.root)
    self.f.write(T.HOOK, hook).chmod(0o644)
    self.guards = self.f.write("var/lib/omarchy/t2-hibernate-trial/guards/trial-consumed.json", b"immutable guard")
    self.calls = []

  def check(self, root, action, phase):
    self.calls.append((action, phase))
    self.assertTrue((root / T.DB_LOCK).is_file())
    held = os.open(root / T.PHYSICAL_LOCK, os.O_RDONLY)
    try:
      with self.assertRaises(BlockingIOError): fcntl.flock(held, fcntl.LOCK_EX | fcntl.LOCK_NB)
    finally: os.close(held)
    source_default = (action == "activation" and phase == "after") or (action == "deactivation" and phase == "before")
    F.PRODUCT.TRIAL._verify_deployment(root, self.f.config, self.f.report, source_default=source_default)

  def run_action(self, action="activation", check=None):
    extra = {"maintenance_resume": lambda: dict(RESUME)} if action == "maintenance" else {}
    return T.transition(self.root, action, precheck=self.check if check is None else check, **extra)

  def pending(self, action): return self.root / T.PENDINGS[action]

  def test_activation_then_exact_fallback_preserves_all_authority_and_evidence(self):
    opt = (self.root / T.OPT_IN).stat().st_ino
    first = self.run_action()
    self.assertFalse(first["live_execution"])
    self.assertFalse(first["qualification_issued"])
    self.assertEqual((self.root / T.P.LIMINE).read_bytes(), self.f.proposal["after"])
    self.assertEqual((self.root / T.OPT_IN).stat().st_ino, opt)
    self.assertFalse(self.pending("activation").exists())
    second = self.run_action("deactivation")
    self.assertEqual((self.root / T.P.LIMINE).read_bytes(), self.f.before)
    self.assertFalse((self.root / T.OPT_IN).exists())
    self.assertFalse((self.root / T.P.POLICY).exists())
    self.assertFalse((self.root / T.DB_LOCK).exists())
    self.assertEqual((self.root / T.P.RECEIPT).read_bytes(), self.f.raw)
    self.assertEqual(self.guards.read_bytes(), b"immutable guard")
    self.assertEqual((self.root / T.P.BACKUP).read_bytes(), self.f.before)
    for value in (first, second):
      history = self.root / T.HISTORY / value["transition_id"]
      self.assertEqual(json.loads((history / "policy.json").read_bytes()), self.f.policy)
      self.assertTrue((history / "completion.json").is_file())
    self.assertEqual(T.G.check(self.root)["default_entry"], 2)

  def test_live_root_alias_relative_and_symlink_roots_refused_without_open(self):
    alias = self.root.parent / "root-alias"
    alias.symlink_to("/")
    with patch.object(T.os, "open", side_effect=AssertionError("no live filesystem open")):
      for root in ("/", "/tmp/..", "relative", alias):
        with self.assertRaises(ValueError): T.transition(root, "activation", precheck=lambda *args: None)

  def test_existing_pacman_lock_and_busy_physical_lock_never_deleted_or_retried(self):
    db = self.f.write(T.DB_LOCK, b"existing transaction")
    with self.assertRaises(FileExistsError): self.run_action()
    self.assertEqual(db.read_bytes(), b"existing transaction")
    db.unlink()
    held = os.open(self.root / T.PHYSICAL_LOCK, os.O_RDONLY)
    try:
      fcntl.flock(held, fcntl.LOCK_EX | fcntl.LOCK_NB)
      with self.assertRaises(BlockingIOError): self.run_action()
    finally: os.close(held)
    self.assertFalse(db.exists())
    self.assertFalse(self.pending("activation").exists())

  def test_unreviewed_hook_invalid_policy_and_preexisting_pending_block_before_boot_write(self):
    original = (self.root / T.HOOK).read_bytes()
    (self.root / T.HOOK).write_bytes(b"modified hook")
    with self.assertRaises(ValueError): self.run_action()
    (self.root / T.HOOK).write_bytes(original)
    review = self.root / T.REVIEW
    raw = review.read_bytes()
    review.write_bytes(json.dumps({**self.f.policy, "approved": False}).encode())
    with self.assertRaises(ValueError): self.run_action()
    review.write_bytes(raw)
    self.f.write(T.PENDINGS["deactivation"], b"interrupted")
    with self.assertRaises(ValueError): self.run_action()
    self.assertEqual((self.root / T.P.LIMINE).read_bytes(), self.f.before)

  def test_efi_slots_unresolved_ledger_and_fifo_evidence_fail_before_pending(self):
    slot = self.f.write(T.G.EFI / T.PRODUCT.HOST.CT.SOURCE_VARIABLE, b"owned or foreign stage")
    with self.assertRaises(ValueError): self.run_action()
    slot.unlink()
    journal = self.f.write(T.P.STATE / "ledger/.pending-io", b"interrupted")
    with self.assertRaises(ValueError): self.run_action()
    journal.unlink()
    review = self.root / T.REVIEW
    review.unlink()
    os.mkfifo(review, mode=0o600)
    with self.assertRaises(ValueError): self.run_action()
    self.assertFalse(self.pending("activation").exists())

  def test_conf_drift_after_precheck_and_after_postcheck_preserves_pending(self):
    def before_drift(root, action, phase):
      self.check(root, action, phase)
      if phase == "before": (root / T.P.LIMINE).write_bytes(self.f.before + b"#foreign writer\n")
    with self.assertRaises(ValueError): self.run_action(check=before_drift)
    self.assertTrue(self.pending("activation").exists())
    with self.assertRaises(ValueError): self.run_action()

  def test_final_after_byte_drift_cannot_publish_completion(self):
    def drift(root, action, phase):
      self.check(root, action, phase)
      if phase == "after": (root / T.P.LIMINE).write_bytes(self.f.proposal["after"] + b"#foreign writer\n")
    with self.assertRaises(ValueError): self.run_action(check=drift)
    self.assertTrue(self.pending("activation").exists())
    self.assertFalse(any((self.root / T.HISTORY).glob("*/completion.json")))

  def test_deactivation_fault_after_marker_removal_preserves_pending(self):
    self.run_action()
    def fault(*args, **kwargs): raise OSError("after opt-in removal")
    with patch.object(T, "_replace", side_effect=fault):
      with self.assertRaises(OSError): self.run_action("deactivation")
    self.assertFalse((self.root / T.OPT_IN).exists())
    self.assertTrue((self.root / T.P.POLICY).exists())
    self.assertTrue(self.pending("deactivation").exists())
    with self.assertRaises(ValueError): T.G.check(self.root)

  def test_completion_fault_never_blindly_retries(self):
    original = T._new
    def fault(path, *args, **kwargs):
      if path.name == "completion.json": raise OSError("completion publication fault")
      return original(path, *args, **kwargs)
    with patch.object(T, "_new", side_effect=fault):
      with self.assertRaises(OSError): self.run_action()
    self.assertEqual((self.root / T.P.LIMINE).read_bytes(), self.f.proposal["after"])
    self.assertTrue(self.pending("activation").exists())
    with self.assertRaises(ValueError): self.run_action()

  def test_deactivation_fault_after_policy_retirement_still_blocks_updates(self):
    self.run_action()
    def fail(root, action, phase):
      self.check(root, action, phase)
      if phase == "after": raise OSError("post-retirement fault")
    with self.assertRaises(OSError): self.run_action("deactivation", check=fail)
    self.assertFalse((self.root / T.P.POLICY).exists())
    self.assertFalse((self.root / T.OPT_IN).exists())
    self.assertEqual((self.root / T.P.LIMINE).read_bytes(), self.f.before)
    self.assertTrue(self.pending("deactivation").exists())
    with self.assertRaises(ValueError): T.G.check(self.root)

  def test_conf_fsync_failure_preserves_changed_bytes_and_pending(self):
    original = T._sync
    def fail(directory):
      if directory == self.root / "boot" and (self.root / T.P.LIMINE).read_bytes() == self.f.proposal["after"]:
        raise OSError("post-replacement fsync fault")
      return original(directory)
    with patch.object(T, "_sync", side_effect=fail):
      with self.assertRaises(OSError): self.run_action()
    self.assertEqual((self.root / T.P.LIMINE).read_bytes(), self.f.proposal["after"])
    self.assertTrue(self.pending("activation").exists())

  def test_pending_cleanup_fsync_fault_restores_pending_while_both_locks_held(self):
    original = T._sync
    failed = []
    def fail(directory):
      if directory == self.root / T.P.STATE and not self.pending("activation").exists() and not failed and any((self.root / T.HISTORY).glob("*/completion.json")):
        self.assertTrue((self.root / T.DB_LOCK).is_file())
        failed.append(True)
        raise OSError("pending cleanup fsync fault")
      return original(directory)
    with patch.object(T, "_sync", side_effect=fail):
      with self.assertRaises(OSError): self.run_action()
    self.assertTrue(self.pending("activation").exists())
    self.assertFalse((self.root / T.DB_LOCK).exists())
    with self.assertRaises(ValueError): self.run_action()

  def test_foreign_pacman_lock_substitution_is_preserved_with_pending(self):
    def replace_lock(root, action, phase):
      self.check(root, action, phase)
      if phase == "after":
        (root / T.DB_LOCK).rename(root / T.DB_LOCK.with_name("owned-lock-retained"))
        (root / T.DB_LOCK).write_bytes(b"foreign transaction")
    with self.assertRaises(ValueError): self.run_action(check=replace_lock)
    self.assertEqual((self.root / T.DB_LOCK).read_bytes(), b"foreign transaction")
    self.assertTrue(self.pending("activation").exists())

  def test_fixture_maintenance_reuses_deactivation_and_binds_retained_authority(self):
    self.run_action()
    policy_raw = (self.root / T.P.POLICY).read_bytes()
    runtime_raw = (self.root / T.P.STATE / "runtime-deployment-review.json").read_bytes()
    result = self.run_action("maintenance")
    self.assertEqual(result["action"], "deactivation")
    self.assertEqual(self.calls[-2:], [("deactivation", "before"), ("deactivation", "after")])
    self.assertFalse((self.root / T.OPT_IN).exists())
    self.assertFalse((self.root / T.P.POLICY).exists())
    self.assertEqual((self.root / T.P.LIMINE).read_bytes(), self.f.before)
    self.assertFalse(self.pending("deactivation").exists())
    self.assertFalse((self.root / T.DB_LOCK).exists())
    marker = (self.root / T.MAINTENANCE).read_bytes()
    archive = self.root / T.HISTORY / result["transition_id"]
    self.assertEqual((archive / "maintenance-intent.json").read_bytes(), marker)
    self.assertEqual(T.P.digest(marker), result["maintenance_intent_sha256"])
    self.assertEqual(json.loads((archive / "intent.json").read_bytes())["action"], "deactivation")
    self.assertEqual(json.loads((archive / "completion.json").read_bytes())["action"], "deactivation")
    intent = json.loads(marker)
    self.assertEqual(intent, {"protocol": T.MAINTENANCE_SCHEMA, "transition_id": result["transition_id"],
      "old_policy_sha256": T.P.digest(policy_raw), "runtime_review_sha256": T.P.digest(runtime_raw),
      "staged_receipt_sha256": T.P.digest(self.f.raw), "fallback_limine_sha256": T.P.digest(self.f.before),
      "deactivation_completion_sha256": T.P.digest((archive / "completion.json").read_bytes())})
    self.assertEqual(marker, T._encoded(intent))
    self.assertEqual(self.guards.read_bytes(), b"immutable guard")

  def test_maintenance_marker_is_refused_by_every_new_transition(self):
    marker = self.f.write(T.MAINTENANCE, b"foreign or interrupted")
    for action in ("activation", "deactivation", "maintenance"):
      with self.subTest(action=action), self.assertRaisesRegex(ValueError, "maintenance intent"):
        self.run_action(action)
      self.assertEqual(marker.read_bytes(), b"foreign or interrupted")
      self.assertFalse((self.root / T.DB_LOCK).exists())
      self.assertFalse(self.pending("activation").exists())

  def test_private_live_maintenance_refuses_before_any_host_open(self):
    with patch.object(T.os, "open", side_effect=AssertionError("no live open")):
      with self.assertRaisesRegex(ValueError, "Live maintenance entry"):
        T._transition(Path("/"), "maintenance", precheck=lambda *args: None, guard=lambda: None)

  def test_durable_veto_refuses_special_or_linked_leaf_without_opening_device(self):
    path = self.root / T.MAINTENANCE
    os.mkfifo(path, 0o600)
    try:
      with self.assertRaisesRegex(ValueError, "exact private repair"):
        T._veto(self.root, b"expected", durable=True)
      self.assertTrue(stat.S_ISFIFO(path.lstat().st_mode))
    finally: path.unlink()
    path.write_bytes(b"expected")
    path.chmod(0o600)
    link = path.with_name("foreign-link")
    os.link(path, link)
    with self.assertRaisesRegex(ValueError, "exact private repair"):
      T._veto(self.root, b"expected", durable=True)
    self.assertEqual(path.read_bytes(), b"expected")

  def test_maintenance_marker_is_durable_before_deactivation_pending_retirement(self):
    self.run_action()
    events = []
    original_new, original_sync = T._new, T._sync
    def publish(path, raw, mode=0o600):
      if path.name == "maintenance-intent.json": events.append("archived")
      if path == self.root / T.MAINTENANCE:
        self.assertEqual(events, ["archived"])
        self.assertTrue(self.pending("deactivation").exists())
        self.assertTrue((self.root / T.DB_LOCK).exists())
        events.append("marker")
      return original_new(path, raw, mode)
    def sync(directory):
      if directory == self.root / T.P.STATE and not self.pending("deactivation").exists():
        self.assertEqual(events, ["archived", "marker"])
        self.assertEqual((self.root / T.MAINTENANCE).read_bytes(), next((self.root / T.HISTORY).glob("*/maintenance-intent.json")).read_bytes())
        self.assertTrue((self.root / T.DB_LOCK).exists())
        events.append("retired")
      return original_sync(directory)
    with patch.object(T, "_new", side_effect=publish), patch.object(T, "_sync", side_effect=sync):
      self.run_action("maintenance")
    self.assertEqual(events, ["archived", "marker", "retired"])

  def test_resume_tuple_is_archived_exactly_before_intent_and_marker_with_readback(self):
    self.run_action()
    order = []
    original = T._new
    def publish(path, raw, mode=0o600):
      if path.name in ("maintenance-resume.json", "maintenance-intent.json", "package-maintenance.pending"): order.append(path.name)
      return original(path, raw, mode)
    with patch.object(T, "_new", side_effect=publish):
      result = self.run_action("maintenance")
    self.assertEqual(order, ["maintenance-resume.json", "maintenance-intent.json", "package-maintenance.pending"])
    archive = self.root / T.HISTORY / result["transition_id"]
    intent = json.loads((self.root / T.MAINTENANCE).read_bytes())
    raw = (archive / "maintenance-resume.json").read_bytes()
    self.assertEqual(stat.S_IMODE((archive / "maintenance-resume.json").stat().st_mode), 0o600)
    self.assertEqual(raw, T.G._resume_document(result["transition_id"], RESUME, intent))
    self.assertEqual(json.loads(raw)["resume"], RESUME)
    self.assertEqual(T._pinned_resume(self.root), RESUME)
    self.assertNotIn("resume", intent)  # the marker's field set is unchanged; the tuple is a separate bound object

  def test_resume_provider_is_validated_and_a_bad_tuple_publishes_nothing(self):
    self.run_action()
    before = {str(path.relative_to(self.root)): path.read_bytes() for path in self.root.rglob("*") if path.is_file()}
    for bad in ({}, None, {**RESUME, "offset": "7"}, {**RESUME, "device": "/dev/sda"}, {**RESUME, "extra": 1}):
      with self.subTest(bad=bad), self.assertRaises(ValueError):
        T.transition(self.root, "maintenance", precheck=self.check, maintenance_resume=lambda: bad)
      self.assertEqual(before, {str(path.relative_to(self.root)): path.read_bytes() for path in self.root.rglob("*") if path.is_file()})
    self.assertEqual(self.pending("deactivation").exists(), False)  # rejected before any pending or policy write
    with self.assertRaisesRegex(ValueError, "only valid for the maintenance"):
      T.transition(self.root, "activation", precheck=self.check, maintenance_resume=lambda: dict(RESUME))
    with self.assertRaisesRegex(ValueError, "only valid for the maintenance"):
      T.transition(self.root, "maintenance", precheck=self.check, maintenance_resume=RESUME)

  def test_maintenance_publication_faults_keep_old_pending_veto(self):
    for failed_name in ("maintenance-resume.json", "maintenance-intent.json", "package-maintenance.pending"):
      with self.subTest(failed_name=failed_name):
        fixture = Transitions("test_activation_then_exact_fallback_preserves_all_authority_and_evidence")
        fixture.setUp()
        self.addCleanup(fixture.doCleanups)
        fixture.run_action()
        original = T._new
        def fail(path, raw, mode=0o600):
          if path.name == failed_name: raise OSError("maintenance publication fault")
          return original(path, raw, mode)
        with patch.object(T, "_new", side_effect=fail), self.assertRaisesRegex(OSError, "maintenance publication fault"):
          fixture.run_action("maintenance")
        self.assertTrue(fixture.pending("deactivation").exists())
        self.assertFalse((fixture.root / T.DB_LOCK).exists())
        self.assertFalse((fixture.root / T.MAINTENANCE).exists())

  def test_maintenance_completion_readback_fault_keeps_old_pending(self):
    self.run_action()
    original = T._read
    def mismatch(root, relative, **kwargs):
      if Path(relative).name == "completion.json": return b"foreign completion"
      return original(root, relative, **kwargs)
    with patch.object(T, "_read", side_effect=mismatch), self.assertRaisesRegex(ValueError, "completion readback"):
      self.run_action("maintenance")
    self.assertTrue(self.pending("deactivation").exists())
    self.assertFalse((self.root / T.MAINTENANCE).exists())

  def test_maintenance_marker_retirement_and_db_release_faults_fail_closed(self):
    for boundary in ("marker_fsync", "pending_retirement", "db_release"):
      with self.subTest(boundary=boundary):
        fixture = Transitions("test_activation_then_exact_fallback_preserves_all_authority_and_evidence")
        fixture.setUp()
        self.addCleanup(fixture.doCleanups)
        fixture.run_action()
        original = T._sync
        failed = []
        def fail(directory):
          marker = (fixture.root / T.MAINTENANCE).exists()
          pending = fixture.pending("deactivation").exists()
          db = (fixture.root / T.DB_LOCK).exists()
          at_marker = boundary == "marker_fsync" and directory == fixture.root / T.P.STATE and marker and pending
          at_retirement = boundary == "pending_retirement" and directory == fixture.root / T.P.STATE and marker and not pending
          at_db_release = boundary == "db_release" and directory == (fixture.root / T.DB_LOCK).parent and marker and not pending and not db
          if not failed and (at_marker or at_retirement or at_db_release):
            failed.append(True)
            raise OSError("maintenance " + boundary)
          return original(directory)
        with patch.object(T, "_sync", side_effect=fail), self.assertRaisesRegex(OSError, boundary):
          fixture.run_action("maintenance")
        self.assertTrue(failed)
        self.assertTrue(fixture.pending("deactivation").exists())
        self.assertTrue((fixture.root / T.MAINTENANCE).exists())
        self.assertFalse((fixture.root / T.DB_LOCK).exists())


class NativeMaintenance(unittest.TestCase):
  """Internal maintenance core with the native adapter's gate seam, fixtures only."""
  def setUp(self):
    self.fixture = Transitions("test_activation_then_exact_fallback_preserves_all_authority_and_evidence")
    self.fixture.setUp()
    self.addCleanup(self.fixture.doCleanups)
    self.root, self.f = self.fixture.root, self.fixture.f
    self.fixture.run_action()
    self.phases, self.fail = [], {}
    self.image = False

  def gate(self, root, phase):
    self.phases.append(phase)
    if phase == "before":
      # No write of any kind may precede the first prerequisite gate.
      self.assertFalse(any(self.pending_names()))
      self.assertFalse((root / T.MAINTENANCE).exists())
    if phase == "final":
      self.assertTrue((root / T.MAINTENANCE).exists())
      self.assertTrue(self.fixture.pending("deactivation").exists())
    if phase in self.fail: raise ValueError("injected " + phase)
    T.verify_fallback(root, T._read(root, T.P.BACKUP) if phase == "before" else None)
    if self.image and phase in ("final", "retained"): raise ValueError("saved image present")

  def pending_names(self): return [self.fixture.pending(name).exists() for name in T.PENDINGS]

  def run_maintenance(self):
    return T._transition(self.root, "maintenance", precheck=self.fixture.check, guard=lambda: None, maintenance_gate=self.gate,
                          maintenance_resume=lambda: dict(RESUME))

  def tree(self):
    return {str(path.relative_to(self.root)): path.read_bytes() for path in sorted(self.root.rglob("*"))
            if path.is_file() and path != self.root / T.DB_LOCK}

  def new(self):
    other = NativeMaintenance("test_happy_path_publishes_durable_marker_and_vetoes_every_route")
    other.setUp()
    self.addCleanup(other.doCleanups)
    return other

  def test_happy_path_publishes_durable_marker_and_vetoes_every_route(self):
    result = self.run_maintenance()
    self.assertEqual(self.phases, ["before", "after", "final"])
    self.assertTrue((self.root / T.MAINTENANCE).is_file())
    self.assertFalse(any(self.pending_names()))
    self.assertFalse((self.root / T.DB_LOCK).exists())
    self.assertEqual(stat.S_IMODE((self.root / T.MAINTENANCE).stat().st_mode), 0o600)
    self.assertEqual(T.P.digest((self.root / T.MAINTENANCE).read_bytes()), result["maintenance_intent_sha256"])
    self.assertFalse((self.root / T.OPT_IN).exists())
    self.assertFalse((self.root / T.P.POLICY).exists())
    self.assertEqual(T.verify_fallback(self.root)["classification"], "fallback-bytes-verified")
    with self.assertRaisesRegex(ValueError, "package maintenance"): SLEEP.reject_pending(self.root)
    with self.assertRaisesRegex(ValueError, "package maintenance"): F.PRODUCT.verify_deployment(self.root, self.f.config, self.f.report)
    with self.assertRaisesRegex(ValueError, "maintenance intent"): self.fixture.run_action("activation")

  def test_before_failures_write_nothing(self):
    for failure in ("gate", "image", "inventory"):
      with self.subTest(failure=failure):
        other = self.new()
        if failure == "gate": other.fail["before"] = True
        elif failure == "image":
          original = other.fixture.check
          def image(root, action, phase, original=original):
            original(root, action, phase)
            raise ValueError("saved image present before")
          other.fixture.check = image
        else: next((other.root / T.P.STATE / "runtime").rglob("fixture.py")).write_bytes(b"drifted reviewed code\n")
        before = other.tree()
        with self.assertRaises(ValueError): other.run_maintenance()
        self.assertEqual(other.tree(), before)
        self.assertFalse((other.root / T.MAINTENANCE).exists())
        self.assertFalse(any(other.pending_names()))
        self.assertFalse((other.root / T.DB_LOCK).exists())
        self.assertTrue((other.root / T.OPT_IN).exists())

  def test_after_gate_failure_retains_deactivation_pending_veto_without_marker(self):
    self.fail["after"] = True
    with self.assertRaisesRegex(ValueError, "injected after"): self.run_maintenance()
    self.assertTrue(self.fixture.pending("deactivation").exists())
    self.assertFalse((self.root / T.MAINTENANCE).exists())
    self.assertEqual((self.root / T.P.LIMINE).read_bytes(), self.f.before)
    with self.assertRaisesRegex(ValueError, "package maintenance"): SLEEP.reject_pending(self.root)
    self.assertFalse((self.root / T.DB_LOCK).exists())

  def test_final_failures_retain_marker_and_old_pending_before_retirement(self):
    for failure in ("gate", "image", "uki"):
      with self.subTest(failure=failure):
        other = self.new()
        if failure == "gate": other.fail["final"] = True
        elif failure == "image": other.image = True
        else:
          original = other.gate
          def swap(root, phase, original=original):
            if phase == "final": (root / T.PRODUCTION).write_bytes(b"different production image")
            original(root, phase)
          other.gate = swap
        with self.assertRaises(ValueError): other.run_maintenance()
        self.assertTrue((other.root / T.MAINTENANCE).exists())
        self.assertTrue(other.fixture.pending("deactivation").exists())
        self.assertFalse((other.root / T.DB_LOCK).exists())
        with self.assertRaisesRegex(ValueError, "package maintenance"): SLEEP.reject_pending(other.root)

  def test_fallback_rejects_uki_mismatch_wrong_default_and_missing_image(self):
    backup = T._read(self.root, T.P.BACKUP)
    self.assertEqual(T.verify_fallback(self.root, backup)["limine"]["sha256"], T.P.digest(self.f.before))
    original = (self.root / T.PRODUCTION).read_bytes()
    (self.root / T.PRODUCTION).write_bytes(original + b"x")
    with self.assertRaisesRegex(ValueError, "does not bind"): T.verify_fallback(self.root, backup)
    (self.root / T.PRODUCTION).write_bytes(original)
    for mutated in (backup.replace(b"default_entry: 2", b"default_entry: 3"),
                    backup.replace(b"default_entry: 2", b"default_entry: 2\nremember_last_entry: yes")):
      with self.assertRaises(ValueError): T.verify_fallback(self.root, mutated)
    (self.root / T.PRODUCTION).unlink()
    with self.assertRaises(FileNotFoundError): T.verify_fallback(self.root, backup)

  def test_lock_contention_never_publishes_anything(self):
    before = self.tree()
    held = os.open(self.root / T.PHYSICAL_LOCK, os.O_RDONLY)
    try:
      fcntl.flock(held, fcntl.LOCK_EX | fcntl.LOCK_NB)
      with self.assertRaises(BlockingIOError): self.run_maintenance()
    finally: os.close(held)
    db = self.f.write(T.DB_LOCK, b"pacman owns this")
    with self.assertRaises(FileExistsError): self.run_maintenance()
    self.assertEqual(db.read_bytes(), b"pacman owns this")
    db.unlink()
    self.assertEqual(self.tree(), before)
    self.assertEqual(self.phases, [])

  REAL = hasattr(T.G, "_maintenance")

  def reenter(self):
    return T._verify_existing_maintenance(self.root, guard=lambda: None, gate=self.gate)

  def test_reentry_wiring_runs_guard_validator_under_locks_then_retained_gate(self):
    self.run_maintenance()
    marker = (self.root / T.MAINTENANCE).read_bytes()
    settled, events = self.tree(), []
    def validator(root):
      events.append("validator")
      self.assertTrue((root / T.DB_LOCK).is_file())
      held = os.open(root / T.PHYSICAL_LOCK, os.O_RDONLY)
      try:
        with self.assertRaises(BlockingIOError): fcntl.flock(held, fcntl.LOCK_EX | fcntl.LOCK_NB)
      finally: os.close(held)
      return {"transition_id": json.loads(marker)["transition_id"]}
    self.phases.clear()
    with patch.object(T.G, "_maintenance", validator, create=True):
      result = self.reenter()
    self.assertEqual((events, self.phases), (["validator"], ["retained"]))
    self.assertTrue(result["already_inactive"])
    self.assertEqual(result["maintenance_intent_sha256"], T.P.digest(marker))
    self.assertEqual(self.tree(), settled)
    self.assertFalse((self.root / T.DB_LOCK).exists())
    # Validator or retained-gate failure propagates, never touching the marker.
    with patch.object(T.G, "_maintenance", side_effect=ValueError("guard refuses"), create=True):
      with self.assertRaisesRegex(ValueError, "guard refuses"): self.reenter()
    self.fail_gate = True
    self.fail["retained"] = True
    with patch.object(T.G, "_maintenance", validator, create=True):
      with self.assertRaisesRegex(ValueError, "injected retained"): self.reenter()
    self.assertEqual(self.tree(), settled)
    self.assertFalse((self.root / T.DB_LOCK).exists())

  def test_reentry_refuses_without_guard_validator_or_marker(self):
    with patch.object(T.G, "_maintenance", None, create=True):
      with self.assertRaisesRegex(ValueError, "lacks the exact maintenance validator"): self.reenter()
    with patch.object(T.G, "_maintenance", lambda root: {}, create=True):
      with self.assertRaises(FileNotFoundError): self.reenter()
    self.assertFalse((self.root / T.MAINTENANCE).exists())
    self.assertFalse((self.root / T.DB_LOCK).exists())

  def test_idempotent_rerun_refuses_rewrite(self):
    self.run_maintenance()
    settled = self.tree()
    with self.assertRaisesRegex(ValueError, "maintenance intent"): self.run_maintenance()
    self.assertEqual(self.tree(), settled)

  def coherent_update(self):
    """Simulate an OS/kernel update: new production UKI and its matching stock entry hash."""
    old = (self.root / T.PRODUCTION).read_bytes()
    new = b"updated production image"
    limine = (self.root / T.P.LIMINE).read_bytes()
    (self.root / T.PRODUCTION).write_bytes(new)
    (self.root / T.P.LIMINE).write_bytes(limine.replace(hashlib.blake2b(old).hexdigest().encode(), hashlib.blake2b(new).hexdigest().encode()))

  @unittest.skipUnless(REAL, "requires the update guard's exact maintenance validator")
  def test_reentry_reuses_guard_validator_and_accepts_coherent_new_stock(self):
    self.run_maintenance()
    settled = self.tree()
    self.phases.clear()
    self.assertTrue(self.reenter()["already_inactive"])
    self.assertEqual((self.phases, self.tree()), (["retained"], settled))
    self.coherent_update()
    updated = self.tree()
    self.assertTrue(self.reenter()["already_inactive"])
    self.assertEqual(self.tree(), updated)
    self.assertEqual(T._pinned_resume(self.root), RESUME)  # re-entry after the update reads the archived tuple, never a fresh audit
    self.assertFalse((self.root / T.DB_LOCK).exists())

  @unittest.skipUnless(REAL, "requires the update guard's exact maintenance validator")
  def test_snapshot_churn_never_blocks_reentry_or_fallback_but_snapshot_default_does(self):
    self.run_maintenance()
    marker = (self.root / T.MAINTENANCE).read_bytes()
    def rewrite(numbers, reverse=False, kernel=None):
      limine = with_snapshots((self.root / T.P.LIMINE).read_bytes(), numbers, reverse)
      if kernel is not None:
        limine = limine.replace(hashlib.blake2b((self.root / T.PRODUCTION).read_bytes()).hexdigest().encode(), hashlib.blake2b(kernel).hexdigest().encode())
        (self.root / T.PRODUCTION).write_bytes(kernel)
      self.f.write(T.P.LIMINE, limine)
    stages = ((lambda: rewrite([1]), "first snapshot"), (lambda: rewrite([1, 2]), "second snapshot added"),
              (lambda: rewrite([2]), "old snapshot cleaned up"), (lambda: rewrite([2, 3, 4], reverse=True), "reordered block"),
              (lambda: rewrite([5], kernel=b"kernel update with snapshot churn"), "kernel update plus churn"), (lambda: rewrite([]), "all snapshots removed"))
    for change, label in stages:
      with self.subTest(label):
        change()
        self.assertEqual(T.verify_fallback(self.root)["classification"], "fallback-bytes-verified")
        self.assertTrue(self.reenter()["already_inactive"])
    self.assertEqual((self.root / T.MAINTENANCE).read_bytes(), marker)
    rewrite([1, 2])
    good = (self.root / T.P.LIMINE).read_bytes()
    for label, text in (("snapshot promoted to default", good.replace(b"default_entry: 2", b"default_entry: 5")),
                        ("second default inside the region", good.replace(b"comment: 4.0.2-1", b"default_entry: 5", 1))):
      with self.subTest(label):
        self.f.write(T.P.LIMINE, text)
        with self.assertRaisesRegex(ValueError, "canonical stock default 2"): T.verify_fallback(self.root)
        with self.assertRaisesRegex(ValueError, "canonical stock default 2"): self.reenter()
    self.f.write(T.P.LIMINE, good)
    self.assertTrue(self.reenter()["already_inactive"])

  # --- generation baseline sidecar -------------------------------------------------
  def baseline(self): return {name: {"identity": name, "sha256": T.P.digest(name.encode())} for name in T.BASELINE_ITEMS}

  def publish(self, provider=None, order=None):
    calls = self.phases
    calls.clear()
    def called():
      # Captured pre-write: the qualified generation is still active, nothing is published yet.
      self.assertEqual(calls, ["before"])
      self.assertFalse(any(self.pending_names()) or (self.root / T.MAINTENANCE).exists())
      self.assertTrue((self.root / T.OPT_IN).exists())
      return (self.baseline if provider is None else provider)()
    original = T._new
    def record(path, raw, mode=0o600):
      if order is not None and path.name in ("maintenance-resume.json", T.BASELINE_NAME, "maintenance-intent.json", "package-maintenance.pending"): order.append(path.name)
      return original(path, raw, mode)
    with patch.object(T, "_new", side_effect=record):
      return T._transition(self.root, "maintenance", precheck=self.fixture.check, guard=lambda: None, maintenance_gate=self.gate,
                           maintenance_resume=lambda: dict(RESUME), maintenance_baseline=called)

  def test_baseline_is_archived_exactly_before_intent_and_marker_and_guard_ignores_it(self):
    order = []
    result = self.publish(order=order)
    self.assertEqual(order, ["maintenance-resume.json", "generation-baseline.json", "maintenance-intent.json", "package-maintenance.pending"])
    archive = self.root / T.HISTORY / result["transition_id"]
    marker = (self.root / T.MAINTENANCE).read_bytes()
    intent = json.loads(marker)
    raw = (archive / T.BASELINE_NAME).read_bytes()
    self.assertEqual(stat.S_IMODE((archive / T.BASELINE_NAME).stat().st_mode), 0o600)
    expected_items = {**self.baseline(), "limine": {"exact_sha256": T.P.digest(self.f.before), "projection_sha256": T.P.digest(T._encoded(T.stock_projection(self.f.before)))}}
    document = {"protocol": "omarchy-t2-generation-baseline-v1", "transition_id": result["transition_id"], "maintenance_intent_sha256": T.P.digest(marker),
                "old_policy_sha256": intent["old_policy_sha256"], "staged_receipt_sha256": intent["staged_receipt_sha256"],
                "deactivation_completion_sha256": intent["deactivation_completion_sha256"], "items": expected_items}
    self.assertEqual(raw, T._encoded(document))
    self.assertEqual(T.read_baseline(self.root), expected_items)
    self.assertEqual(set(intent), {"protocol", "transition_id", "old_policy_sha256", "runtime_review_sha256", "staged_receipt_sha256",
                                    "fallback_limine_sha256", "deactivation_completion_sha256"})  # marker field set unchanged
    self.assertNotIn(b"cryptkey", raw)
    if self.REAL:  # the guard's exact validator neither requires nor reads the sidecar
      self.assertEqual(T.G._maintenance(self.root)["resume"], RESUME)
      (archive / T.BASELINE_NAME).write_bytes(b"not even json")
      self.assertEqual(T.G._maintenance(self.root)["resume"], RESUME)
      (archive / T.BASELINE_NAME).unlink()
      self.assertEqual(T.G._maintenance(self.root)["resume"], RESUME)

  def test_stock_identity_is_computed_before_the_first_write(self):
    order = []
    real_identity, original = T.stock_identity, T._new
    def identity(raw):
      order.append("stock_identity")
      return real_identity(raw)
    def record(path, raw, mode=0o600):
      order.append(path.name)
      return original(path, raw, mode)
    with patch.object(T, "stock_identity", side_effect=identity), patch.object(T, "_new", side_effect=record):
      T._transition(self.root, "maintenance", precheck=self.fixture.check, guard=lambda: None, maintenance_gate=self.gate,
                    maintenance_resume=lambda: dict(RESUME), maintenance_baseline=self.baseline)
    self.assertEqual(order.count("stock_identity"), 1)
    self.assertEqual(order.index("stock_identity"), 0)  # ahead of the deactivation pending and every archive write

  def test_unusable_stock_projection_fails_before_any_write(self):
    before = self.tree()
    with patch.object(T, "stock_identity", side_effect=ValueError("no stock projection")):
      with self.assertRaisesRegex(ValueError, "no stock projection"):
        T._transition(self.root, "maintenance", precheck=self.fixture.check, guard=lambda: None, maintenance_gate=self.gate,
                      maintenance_resume=lambda: dict(RESUME), maintenance_baseline=self.baseline)
    self.assertEqual(self.tree(), before)

  def test_baseline_write_crash_leaves_no_marker_and_keeps_the_old_pending_veto(self):
    original = T._new
    def fault(path, *args, **kwargs):
      if path.name == T.BASELINE_NAME: raise OSError("baseline write fault")
      return original(path, *args, **kwargs)
    with patch.object(T, "_new", side_effect=fault):
      with self.assertRaisesRegex(OSError, "baseline write fault"):
        T._transition(self.root, "maintenance", precheck=self.fixture.check, guard=lambda: None, maintenance_gate=self.gate,
                      maintenance_resume=lambda: dict(RESUME), maintenance_baseline=self.baseline)
    archive = next((self.root / T.HISTORY).glob("*/completion.json")).parent
    self.assertFalse((self.root / T.MAINTENANCE).exists())
    self.assertFalse((archive / "maintenance-intent.json").exists() or (archive / T.BASELINE_NAME).exists())
    self.assertTrue(self.fixture.pending("deactivation").exists())
    with self.assertRaisesRegex(ValueError, "package maintenance"): SLEEP.reject_pending(self.root)
    self.assertFalse((self.root / T.DB_LOCK).exists())

  def test_baseline_readback_fault_and_partial_file_never_reach_a_marker(self):
    original = T._read
    def wrong(root, relative, *args, **kwargs):
      raw = original(root, relative, *args, **kwargs)
      return raw + b" " if Path(relative).name == T.BASELINE_NAME else raw
    with patch.object(T, "_read", side_effect=wrong):
      with self.assertRaisesRegex(ValueError, "baseline readback differs"):
        T._transition(self.root, "maintenance", precheck=self.fixture.check, guard=lambda: None, maintenance_gate=self.gate,
                      maintenance_resume=lambda: dict(RESUME), maintenance_baseline=self.baseline)
    self.assertFalse((self.root / T.MAINTENANCE).exists())
    self.assertTrue(self.fixture.pending("deactivation").exists())

  def test_bad_baseline_provider_publishes_nothing(self):
    good = self.baseline()
    bad = {"missing item": {k: v for k, v in good.items() if k != "kernel"}, "extra item": {**good, "extra": {}}, "limine supplied by provider": {**good, "limine": {}},
           "non-dict item": {**good, "kernel": "x"}, "float": {**good, "kernel": {"x": 1.5}}, "non-string key": {**good, "kernel": {1: "x"}},
           "object": {**good, "kernel": {"x": object()}}, "tuple": {**good, "kernel": {"x": (1,)}}, "not a dict": [], "none": None}
    before = self.tree()
    for label, value in bad.items():
      with self.subTest(label), self.assertRaises(ValueError): self.publish(lambda value=value: value)
      self.assertEqual(self.tree(), before)
      self.assertFalse(any(self.pending_names()) or (self.root / T.MAINTENANCE).exists() or (self.root / T.DB_LOCK).exists())
    def refuses(): raise ValueError("provider refused")
    with self.assertRaisesRegex(ValueError, "provider refused"): self.publish(refuses)
    self.assertEqual(self.tree(), before)
    huge = {**good, "kernel": {"blob": "x" * (T.P.MAX_BYTES + 1)}}
    with self.assertRaises(ValueError): self.publish(lambda: huge)
    self.assertEqual(self.tree(), before)
    self.assertFalse(any(self.pending_names()) or (self.root / T.MAINTENANCE).exists())
    for invalid in ("not callable", {}):
      with self.assertRaisesRegex(ValueError, "only valid for the maintenance|Maintenance baseline provider"):
        T._transition(self.root, "maintenance", precheck=self.fixture.check, guard=lambda: None, maintenance_gate=self.gate, maintenance_baseline=invalid)
    with self.assertRaisesRegex(ValueError, "only valid for the maintenance"):
      T._transition(self.root, "deactivation", precheck=self.fixture.check, guard=lambda: None, maintenance_baseline=self.baseline)
    self.assertEqual(self.tree(), before)

  def test_read_baseline_reports_missing_and_refuses_forged_or_unbound_documents(self):
    self.publish()
    archive = next((self.root / T.HISTORY).glob("*/" + T.BASELINE_NAME)).parent
    path = archive / T.BASELINE_NAME
    good, marker = path.read_bytes(), (self.root / T.MAINTENANCE).read_bytes()
    document = json.loads(good)
    def variant(**changes): return T._encoded({**document, **changes})
    forged = {"not canonical": good + b"\n", "not json": b"{", "wrong protocol": variant(protocol="other"),
              "other transition": variant(transition_id=str(uuid.uuid4())), "other intent": variant(maintenance_intent_sha256="0" * 64),
              "other policy": variant(old_policy_sha256="1" * 64), "extra field": variant(extra=1),
              "tampered item": variant(items={**document["items"], "kernel": {"identity": "kernel", "sha256": "2" * 64}, "extra": {}}),
              "missing limine": variant(items={k: v for k, v in document["items"].items() if k != "limine"}),
              "float": variant(items={**document["items"], "kernel": {"x": 0.5}})}
    for label, raw in forged.items():
      with self.subTest(label):
        path.write_bytes(raw)
        with self.assertRaises(ValueError): T.read_baseline(self.root)
    path.write_bytes(good)
    self.assertEqual(T.read_baseline(self.root), document["items"])
    # Bound to the marker: an equally canonical document for a different intent digest is refused.
    with self.assertRaises(ValueError): T.read_baseline(self.root, marker.replace(b'"old_policy_sha256":"', b'"old_policy_sha256":"0', 1))
    path.unlink()
    with self.assertRaises(FileNotFoundError): T.read_baseline(self.root)

  def test_stock_projection_ignores_snapshot_churn_but_not_the_stock_binding(self):
    base = self.f.before
    churned = with_snapshots(base, [1, 2])
    self.assertNotEqual(T.stock_identity(base)["exact_sha256"], T.stock_identity(churned)["exact_sha256"])
    self.assertEqual(T.stock_identity(base)["projection_sha256"], T.stock_identity(churned)["projection_sha256"])
    self.assertEqual(T.stock_projection(base), T.stock_projection(with_snapshots(base, [7, 8, 9], reverse=True)))
    rehashed = base.replace(hashlib.blake2b((self.root / T.PRODUCTION).read_bytes()).hexdigest().encode(), b"0" * 128)
    self.assertEqual(T.stock_projection(base), T.stock_projection(rehashed))  # the UKI is compared by its own bytes
    with_cmdline = base.replace(b"protocol: efi\n", b"protocol: efi\ncmdline: root=/dev/other\n", 1)
    self.assertNotEqual(T.stock_projection(base), T.stock_projection(with_cmdline))
    for text in (base.replace(b"default_entry: 2", b"default_entry: 3"), churned.replace(b"comment: 4.0.2-1", b"default_entry: 5", 1)):
      with self.assertRaises(ValueError): T.stock_projection(text)

  def test_reentry_refuses_incoherent_or_drifted_state_and_preserves_marker(self):
    self.run_maintenance()
    marker = (self.root / T.MAINTENANCE).read_bytes()
    production = (self.root / T.PRODUCTION).read_bytes()
    (self.root / T.PRODUCTION).write_bytes(b"kernel updated but stock entry not")
    with self.assertRaises(ValueError): self.reenter()
    (self.root / T.PRODUCTION).write_bytes(production)
    self.image = True
    with self.assertRaisesRegex(ValueError, "saved image"): self.reenter()
    self.image = False
    self.f.write(T.OPT_IN, b"").chmod(0o644)
    with self.assertRaises(ValueError): self.reenter()
    (self.root / T.OPT_IN).unlink()
    self.f.write(T.PENDINGS["activation"], b"partial")
    with self.assertRaises(ValueError): self.reenter()
    self.fixture.pending("activation").unlink()
    (self.root / T.MAINTENANCE).write_bytes(marker + b" ")
    with self.assertRaises(ValueError): self.reenter()
    (self.root / T.MAINTENANCE).write_bytes(marker)
    self.assertTrue(self.reenter()["already_inactive"])
    self.assertFalse((self.root / T.DB_LOCK).exists())

  def complete(self, pinned=None):
    active = T.G.ACTIVE
    value = tuple(active)
    try: return T._complete_interrupted_maintenance(self.root, guard=lambda: None, gate=self.gate, pinned=pinned)
    finally:  # the guard's source-state list is never mutated, on success or refusal
      self.assertIs(T.G.ACTIVE, active)
      self.assertEqual(tuple(T.G.ACTIVE), value)

  def interrupt(self, how="gate"):
    """Publish maintenance, then leave marker + deactivation pending exactly as a crash would."""
    if how == "gate":
      self.fail["final"] = True
      with self.assertRaisesRegex(ValueError, "injected final"): self.run_maintenance()
      self.fail.clear()
    else:
      real = T._sync
      def crash(directory):
        if Path(directory) == self.root / T.PENDINGS["deactivation"].parent and not self.fixture.pending("deactivation").exists():
          raise OSError("crash at retirement")
        return real(directory)
      with patch.object(T, "_sync", crash), self.assertRaisesRegex(OSError, "crash at retirement"): self.run_maintenance()
    self.assertTrue((self.root / T.MAINTENANCE).exists())
    self.assertTrue(self.fixture.pending("deactivation").exists())
    self.assertFalse((self.root / T.DB_LOCK).exists())
    self.phases.clear()

  def archive(self): return next((self.root / T.HISTORY).iterdir())

  def refuses_unchanged(self, pattern=None):
    before = self.tree()
    with (self.assertRaisesRegex(Exception, pattern) if pattern else self.assertRaises(Exception)): self.complete()
    self.assertEqual(self.tree(), before)
    self.assertFalse((self.root / T.DB_LOCK).exists())

  @unittest.skipUnless(REAL, "requires the update guard's exact maintenance validator")
  def test_interrupted_maintenance_completes_only_the_pending_retirement(self):
    for how in ("gate", "crash"):
      with self.subTest(how=how):
        other = self.new()
        other.interrupt(how)
        with self.assertRaisesRegex(ValueError, "Active or incomplete"): T.G._maintenance(other.root)
        with self.assertRaises(ValueError): other.reenter()
        with self.assertRaisesRegex(ValueError, "Existing package maintenance intent"): other.run_maintenance()
        before = other.tree()
        marker, pending = (other.root / T.MAINTENANCE).read_bytes(), other.fixture.pending("deactivation").read_bytes()
        pinned = {}
        result = other.complete(pinned)
        self.assertTrue(result["completed_interrupted_maintenance"])
        self.assertEqual(pinned["resume"], RESUME)
        self.assertEqual(other.phases, ["final", "retained"])
        self.assertEqual(pinned["resume"], T._pinned_resume(other.root))
        self.assertFalse(other.fixture.pending("deactivation").exists())
        self.assertEqual((other.root / T.MAINTENANCE).read_bytes(), marker)
        self.assertEqual(T.P.digest(marker), result["maintenance_intent_sha256"])
        self.assertEqual(other.tree(), {name: value for name, value in before.items() if not name.endswith("source-default-deactivation.pending")})
        self.assertEqual(T.G._maintenance(other.root)["transition_id"], result["transition_id"])
        self.assertFalse((other.root / T.DB_LOCK).exists())
        self.assertTrue(other.reenter()["already_inactive"])  # second run: nothing pending, plain re-entry
        with self.assertRaises(FileNotFoundError): other.complete()  # the completion itself never runs twice

  @unittest.skipUnless(REAL, "requires the update guard's exact maintenance validator")
  def test_interrupted_maintenance_refuses_mismatch_without_any_change(self):
    self.interrupt()
    pending = self.fixture.pending("deactivation")
    original = pending.read_bytes()
    pending.write_bytes(original.replace(b"deactivation", b"deactivatioN"))
    self.refuses_unchanged("not the archived intent")
    pending.write_bytes(json.dumps(json.loads(original), indent=1).encode())
    self.refuses_unchanged()
    pending.write_bytes(original)
    # transition_id mismatch: a foreign but self-consistent pending id, archive left alone
    swapped = json.loads(original)
    swapped["transition_id"] = str(uuid.uuid4())
    pending.write_bytes(T._encoded(swapped))
    self.refuses_unchanged()
    pending.write_bytes(original)
    # archived intent changed too, pending identical to it: chain to completion/marker breaks
    intent = self.archive() / "intent.json"
    changed = json.loads(original)
    changed["policy_sha256"] = "0" * 64
    intent.write_bytes(T._encoded(changed)); pending.write_bytes(T._encoded(changed))
    self.refuses_unchanged()
    intent.write_bytes(original); pending.write_bytes(original)
    # marker pins a different completion
    marker = (self.root / T.MAINTENANCE).read_bytes()
    (self.root / T.MAINTENANCE).write_bytes(marker + b" ")
    self.refuses_unchanged()
    (self.root / T.MAINTENANCE).write_bytes(marker)
    self.assertEqual(self.phases, [])
    self.assertTrue(self.complete()["completed_interrupted_maintenance"])

  @unittest.skipUnless(REAL, "requires the update guard's exact maintenance validator")
  def test_interrupted_maintenance_refuses_any_other_active_state(self):
    self.interrupt()
    for path, mode in ((T.PENDINGS["activation"], 0o600), (T.RUNTIME_PENDINGS[0], 0o600), (T.RUNTIME_PENDINGS[1], 0o600), (T.P.POLICY, 0o600), (T.OPT_IN, 0o644)):
      with self.subTest(path=path.name):
        extra = self.f.write(path, b"partial")
        extra.chmod(mode)
        self.refuses_unchanged()
        extra.unlink()
    self.assertTrue(self.complete()["completed_interrupted_maintenance"])

  @unittest.skipUnless(REAL, "requires the update guard's exact maintenance validator")
  def test_interrupted_maintenance_refuses_failed_gates_and_saved_image_without_change(self):
    self.interrupt()
    self.image = True
    self.refuses_unchanged("saved image")
    self.image = False
    self.fail["final"] = True
    self.refuses_unchanged("injected final")
    self.fail.clear()
    (self.root / T.PRODUCTION).write_bytes(b"different production image")
    self.refuses_unchanged()

  @unittest.skipUnless(REAL, "requires the update guard's exact maintenance validator")
  def test_retained_failure_after_retirement_reinstates_identical_pending(self):
    self.interrupt()
    self.fail["retained"] = True
    self.refuses_unchanged("injected retained")
    self.assertEqual(self.phases, ["final", "retained"])

  @unittest.skipUnless(REAL, "requires the update guard's exact maintenance validator")
  def test_interrupted_maintenance_lock_contention_and_guard_restore(self):
    self.interrupt()
    active = tuple(T.G.ACTIVE)
    before = self.tree()
    held = os.open(self.root / T.PHYSICAL_LOCK, os.O_RDONLY)
    try:
      fcntl.flock(held, fcntl.LOCK_EX | fcntl.LOCK_NB)
      with self.assertRaises(BlockingIOError): self.complete()
    finally: os.close(held)
    db = self.f.write(T.DB_LOCK, b"pacman owns this")
    with self.assertRaises(FileExistsError): self.complete()
    self.assertEqual(db.read_bytes(), b"pacman owns this")
    db.unlink()
    self.assertEqual(self.tree(), before)
    self.assertEqual(self.phases, [])
    self.assertEqual(tuple(T.G.ACTIVE), active)
    self.complete()
    self.assertEqual(tuple(T.G.ACTIVE), active)  # the relaxation never leaks past the call

  @unittest.skipUnless(REAL, "requires the update guard's exact maintenance validator")
  def test_completion_passes_only_the_deactivation_pending_as_ignore_then_verifies_unrelaxed(self):
    self.interrupt()
    seen, real = [], T.G._maintenance
    with patch.object(T.G, "_maintenance", lambda root, *a, **k: seen.append(k) or real(root, *a, **k)):
      self.complete()
    self.assertEqual(seen, [{"ignore": (T.PENDINGS["deactivation"],)}, {}])

  def test_interrupted_maintenance_completion_needs_native_capability_on_live_root(self):
    noop = lambda *a: None
    for root in (Path("/"), Path("/tmp")):
      with self.assertRaises(ValueError): T._complete_interrupted_maintenance(root, guard=noop, gate=noop)
    with self.assertRaises(ValueError): T._complete_interrupted_maintenance(Path("/"), guard=noop, gate=noop, native=object())
    self.assertFalse(hasattr(T, "complete_interrupted_maintenance"))
    with self.assertRaises(TypeError): T.transition(self.root, "maintenance", precheck=noop, pinned={})

  def test_runtime_pending_markers_refuse_maintenance_with_no_writes(self):
    for relative in T.RUNTIME_PENDINGS:
      with self.subTest(marker=str(relative)):
        other = self.new()
        other.f.write(relative, b"interrupted")
        before = other.tree()
        with self.assertRaisesRegex(ValueError, "Runtime deployment/upgrade pending"): other.run_maintenance()
        self.assertEqual(other.tree(), before)
        self.assertEqual(other.phases, [])
        self.assertFalse((other.root / T.MAINTENANCE).exists())
        self.assertFalse(any(other.pending_names()))
        self.assertFalse((other.root / T.DB_LOCK).exists())
    self.assertEqual(T.RUNTIME_PENDINGS, (T.P.STATE / "runtime-upgrade.pending", T.P.STATE / ".runtime-pending"))

  def test_live_roots_and_arbitrary_callbacks_are_never_accepted(self):
    alias = self.root.parent / "live-alias"
    alias.symlink_to("/")
    noop = lambda *args: None
    with patch.object(T.os, "open", side_effect=AssertionError("no live filesystem open")):
      for root in ("/", "/tmp/..", "relative", alias, Path("/")):
        with self.subTest(root=str(root)):
          with self.assertRaises(ValueError): T.transition(root, "maintenance", precheck=noop)
          with self.assertRaises(ValueError): T._transition(root, "maintenance", precheck=noop, guard=noop, maintenance_gate=noop)
          with self.assertRaises(ValueError): T._transition(root, "maintenance", precheck=noop, guard=noop, maintenance_gate=noop, native=object())
          with self.assertRaises(ValueError): T._verify_existing_maintenance(root, guard=noop, gate=noop)
      with self.assertRaises(ValueError): T._transition(Path("/"), "maintenance", precheck=noop, guard=noop, native=T._NATIVE_MAINTENANCE)
    # The public API cannot receive a gate or capability at all.
    with self.assertRaises(TypeError): T.transition(self.root, "maintenance", precheck=noop, maintenance_gate=noop)
    with self.assertRaises(TypeError): T.transition(self.root, "maintenance", precheck=noop, native=T._NATIVE_MAINTENANCE)
    with self.assertRaisesRegex(ValueError, "only valid for the maintenance"):
      T._transition(self.root, "deactivation", precheck=noop, guard=noop, maintenance_gate=noop)

  def test_native_capability_passes_only_the_entry_check(self):
    # With capability and gate the live root reaches the first inspection, which
    # is stubbed to stop; nothing on the real host is opened or written.
    with patch.object(T, "_locks", side_effect=RuntimeError("stop at exclusion")), patch.object(T.G, "_ancestors", side_effect=RuntimeError("stop at ancestors")):
      with self.assertRaisesRegex(RuntimeError, "stop at"):
        T._transition(Path("/"), "maintenance", precheck=lambda *a: None, guard=lambda: None, maintenance_gate=lambda *a: None, native=T._NATIVE_MAINTENANCE,
                       maintenance_resume=lambda: dict(RESUME), maintenance_baseline=lambda: {})
    with self.assertRaisesRegex(ValueError, "generation baseline"):
      T._transition(Path("/"), "maintenance", precheck=lambda *a: None, guard=lambda: None, maintenance_gate=lambda *a: None, native=T._NATIVE_MAINTENANCE,
                    maintenance_resume=lambda: dict(RESUME))


  @unittest.skipUnless(REAL, "requires the update guard's exact maintenance validator")
  def test_deactivation_after_snapshot_churn_records_the_approved_from_hash_and_the_guard_accepts_the_marker(self):
    self.f.write(T.P.LIMINE, with_snapshots((self.root / T.P.LIMINE).read_bytes(), [1, 2]))
    self.assertNotEqual((self.root / T.P.LIMINE).read_bytes(), self.f.proposal["after"])
    result = self.run_maintenance()
    archive = self.root / T.HISTORY / result["transition_id"]
    intent = json.loads((archive / "intent.json").read_bytes())
    self.assertEqual((intent["from_sha256"], intent["to_sha256"]), (self.f.policy["after_limine_sha256"], self.f.policy["before_limine_sha256"]))
    self.assertEqual((self.root / T.P.LIMINE).read_bytes(), self.f.before)
    self.assertEqual(T.G._maintenance(self.root)["transition_id"], result["transition_id"])  # the guard's exact chain validator accepts it


class ReactivationBytes(unittest.TestCase):
  """The one-line boot-config transform, its canonical checks and the churned-deactivation intent."""
  def setUp(self):
    self.fixture = Transitions("test_activation_then_exact_fallback_preserves_all_authority_and_evidence")
    self.fixture.setUp()
    self.addCleanup(self.fixture.doCleanups)
    self.f, self.root = self.fixture.f, self.fixture.root
    self.entry = self.f.policy["source_entry_id"]

  def test_transform_changes_exactly_one_line_of_the_current_bytes_and_is_canonically_prepare(self):
    proposal = T.P.prepare(self.f.before, self.f.raw)["after"]
    for numbers, reverse in (([], False), ([1], False), ([1, 2], False), ([2, 3, 4], True), ([9, 10, 11, 12, 13], False)):
      with self.subTest(numbers=numbers):
        current = with_snapshots(self.f.before, numbers, reverse)
        self.assertEqual(T.P.limine_canonical(current), self.f.before)
        new = T._to_source_default(current, self.entry)
        self.assertEqual(new, current.replace(b"default_entry: 2\n", b"default_entry: " + self.entry.encode() + b"\n", 1))
        self.assertEqual(T.P.limine_canonical(new), T.P.limine_canonical(proposal))
        T._one_line_change(current, new)
        if not numbers: self.assertEqual(new, proposal)  # no region: the exact approved bytes
        else: self.assertNotEqual(new, proposal)  # never the approved bytes: that would drop the snapshot entries
        self.assertEqual(T._to_stock_default(new, self.entry), current)  # reversal restores the same bytes
        self.assertEqual(T.P.validate({**T.P.prepare(self.f.before, self.f.raw)["policy"], "approved": True}, self.f.before, new, self.f.raw), self.f.before)

  def test_transform_refuses_ambiguous_or_foreign_default_lines(self):
    current = with_snapshots(self.f.before, [1, 2])
    for label, raw in (("second stock default", current + b"default_entry: 2\n"), ("remembered entry", current.replace(b"default_entry: 2\n", b"default_entry: 2\nremember_last_entry: yes\n", 1)),
                       ("indented default", current.replace(b"default_entry: 2\n", b" default_entry: 2\n", 1)), ("no default", current.replace(b"default_entry: 2\n", b"", 1)),
                       ("default inside the region", current.replace(b"     comment: 4.0.2-1\n", b"     default_entry: 2\n", 1)), ("already source", T._to_source_default(current, self.entry))):
      with self.subTest(label), self.assertRaises(ValueError): T._to_source_default(raw, self.entry)
    for label, raw in (("stock", current), ("other entry", current.replace(b"default_entry: 2\n", b"default_entry: other\n", 1))):
      with self.subTest("reverse " + label), self.assertRaises(ValueError): T._to_stock_default(raw, self.entry)
    with self.assertRaisesRegex(ValueError, "exactly one line"): T._one_line_change(b"a\nb\n", b"x\ny\n")
    with self.assertRaisesRegex(ValueError, "exactly one line"): T._one_line_change(b"a\nb\n", b"a\nb\nc\n")

  def test_rollback_never_yields_non_stock_bytes(self):
    current = with_snapshots(self.f.before, [1])
    new = T._to_source_default(current, self.entry)
    broken = new.replace(b"/+Omarchy\n", b"/+Broken\n", 1)
    with self.assertRaises(ValueError): T._to_stock_default(broken, self.entry)  # the guard's stock validator refuses the result

  def test_reactivation_pending_recognizes_only_its_own_protocol(self):
    self.assertFalse(T.reactivation_pending(self.root))
    path = self.root / T.PENDINGS["activation"]
    for raw, expected in ((b"garbage", False), (T._encoded({"protocol": "omarchy-t2-runtime-upgrade-intent-v2"}), False), (T._encoded({"protocol": T.REACTIVATION_SCHEMA}), True)):
      self.fixture.f.write(T.PENDINGS["activation"], raw)
      self.assertIs(T.reactivation_pending(self.root), expected)
      path.unlink()


if __name__ == "__main__": unittest.main()
