"""Shared fixtures for the upstream-model tests: fake ESP, Limine, efivars and product state."""

import hashlib
import importlib.util
import json
import os
from pathlib import Path
import subprocess


script = Path(__file__).resolve().parents[1] / "upstream-model/stage-upstream-model.py"
spec = importlib.util.spec_from_file_location("upstream_model_stage", script)
stage = importlib.util.module_from_spec(spec)
spec.loader.exec_module(stage)
C = stage.C

MACHINE = "0123456789abcdef0123456789abcdef"
BOOT_A = "11111111-2222-3333-4444-555555555555"
BOOT_B = "aaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee"
BOOT_C = "99999999-8888-7777-6666-555555555555"


def sha(data):
  return hashlib.sha256(data).hexdigest()


def efi_string(value):
  return b"\x07\x00\x00\x00" + (value + "\x00").encode("utf-16-le")


def efi_strings(values):
  return b"\x06\x00\x00\x00" + "".join(value + "\x00" for value in values).encode("utf-16-le")


def rejects(action, expected):
  try:
    action()
  except (ValueError, RuntimeError) as error:
    assert expected in str(error), error
  else:
    raise AssertionError("Unsafe action accepted: " + expected)


def objcopy(*arguments):
  subprocess.run(("objcopy", *map(str, arguments)), check=True, capture_output=True)


def region_text(count, tag="a"):
  if count == 0:
    return ""
  text = "     //Snapshots\n     ### Auto-generated by limine-snapper-sync\n     comment: " + str(count) + " snapshots\n"
  for index in range(1, count + 1):
    text += ("     ///" + str(index) + " │ 2026-09-17 17:35:4" + str(index) + "\n     comment: 4.0." + str(index) + "-1\n     ////linux-t2\n"
             "     comment: Kernel version: 7.2.7-test\n     comment: kernel-id=linux-t2\n     protocol: efi\n"
             "     path: boot():/" + MACHINE + "/limine_history/omarchy_linux-t2.efi_sha256_" + tag * 64 + "#" + tag * 128 + "\n"
             "     cmdline: root=/dev/mapper/root rootflags=subvol=/@/.snapshots/" + str(index) + "/snapshot\n")
  return text + "\n"


def limine_text(production_blake2, snapshots=1, tag="a", pair_block=True):
  text = (
    "timeout: 3\ndefault_entry: 2\n"
    "/+Omarchy\n### This OS entry is auto-generated by limine-entry-tool\ncomment: Omarchy\ncomment: machine-id=" + MACHINE + " order-priority=50 \n"
    "  //linux-t2\n  ### This kernel entry is auto-generated by limine-entry-tool\n  comment: kernel-id=linux-t2 \n  protocol: efi\n"
    "  path: boot():/EFI/Linux/omarchy_linux-t2.efi#" + production_blake2 + "\n  cmdline: root=/dev/mapper/root rw\n\n"
    + region_text(snapshots, tag) +
    "/EFI fallback\nprotocol: efi\npath: boot():/EFI/BOOT/BOOTX64.EFI\n"
  )
  if pair_block:
    text += "\n# BEGIN omarchy T2 hibernation pair\n/MBA-T2-hibernation-source-0000000000000000\nprotocol: efi\npath: boot():/EFI/Linux/mba_t2_hibernation_source.efi#" + "0" * 128 + "\n# END omarchy T2 hibernation pair\n"
  return text


RELEASE = "7.2.7-test-t2"
T2BCE_DIR = "usr/lib/modules/" + RELEASE + "/kernel/drivers/staging/t2bce/"


def real_diff():
  """The shape of a real build: three .ko.zst swapped for .ko, the audio .ko and a dependency, the blacklist."""
  swapped = ("t2bce_dma", "t2bce_core", "t2bce_vhci")
  dependency = "usr/lib/modules/" + RELEASE + "/kernel/sound/core/snd-pcm.ko"
  return {
    "removed": [T2BCE_DIR + name + "/" + name + ".ko.zst" for name in swapped],
    "added": [T2BCE_DIR + name + "/" + name + ".ko" for name in swapped] + [T2BCE_DIR + "t2bce_audio/t2bce_audio.ko", dependency, C.BLACKLIST_DESTINATION],
    "changed": [], "audio_dependencies": ["/" + T2BCE_DIR + "t2bce_audio/t2bce_audio.ko", "/" + dependency],
  }


def make_build(directory, production, *, mutate=None):
  directory.mkdir(mode=0o700)
  initrd = directory / C.BUILD_INITRD
  initrd.write_bytes(b"upstream model initramfs")
  image = directory / C.BUILD_IMAGE
  objcopy("--update-section=.initrd=" + str(initrd), production, image)
  data = image.read_bytes()
  provenance = {
    "candidate": C.CANDIDATE, "protocol": C.PROTOCOL, "experiment_id": "upstream-test",
    "candidate_uki_sha256": sha(data), "production_uki_sha256": sha(production.read_bytes()),
    "unchanged_production_sections_sha256": {".linux": sha(b"k"), ".cmdline": sha(b"c")},
    "modified_sections_sha256": None,
    "deltas": {"D1_modules_added": ["t2bce_audio"], "D2_initramfs_blacklist": list(C.BLACKLISTED_MODULES), "build_hook": C.HOOK},
    "kernel_release": RELEASE,
    "initrd_manifest_diff": real_diff(),
    "modules": {name: {"sha256": sha(name.encode()), "srcversion": "SRC" + name} for name in C.T2BCE_MODULES},
    "production_modified": False, "installed": False, "boot_entry_created": False, "hardware_qualified": False,
  }
  if mutate is not None:
    mutate(provenance, image)
    provenance["candidate_uki_sha256"] = provenance.get("candidate_uki_sha256") or sha(image.read_bytes())
  (directory / C.BUILD_PROVENANCE).write_text(json.dumps(provenance))
  for path in (image, initrd, directory / C.BUILD_PROVENANCE):
    path.chmod(0o600)
  return directory


def fixture(base, *, maintenance=True, build=True):
  root = base / "root"
  production = root / "boot/EFI/Linux/omarchy_linux-t2.efi"
  production.parent.mkdir(parents=True)
  kernel, cmdline = base / "kernel", base / "cmdline"
  kernel.write_bytes(b"healthy production kernel")
  cmdline.write_bytes(b"root=/dev/mapper/root resume=/dev/mapper/root resume_offset=5\x00")
  objcopy("--add-section=.linux=" + str(kernel), "--add-section=.cmdline=" + str(cmdline),
          "--add-section=.initrd=" + str(kernel), "/usr/lib/systemd/boot/efi/linuxx64.efi.stub", production)
  limine = root / stage.LIMINE
  original = limine_text(hashlib.blake2b(production.read_bytes()).hexdigest())
  limine.write_text(original)
  selected = root / stage.SELECTED
  selected.parent.mkdir(parents=True)
  selected.write_bytes(efi_string(C.STOCK_ENTRY))
  boot = root / stage.BOOT_ID
  boot.parent.mkdir(parents=True)
  boot.write_text(BOOT_A + "\n")
  if maintenance:
    marker = root / stage.MAINTENANCE
    marker.parent.mkdir(parents=True)
    marker.write_text("pending\n")
  lock = root / stage.PHYSICAL_LOCK
  lock.parent.mkdir(parents=True)
  lock.write_text("")
  (root / stage.DB_LOCK).parent.mkdir(parents=True)
  pair = root / stage.PAIR_STATE
  pair.mkdir(parents=True)
  (pair / "receipt.json").write_text(json.dumps({"images": {"source": {"sha256": "5" * 64}}}))
  (root / "sys/firmware/efi/efivars").mkdir(parents=True, exist_ok=True)
  built = make_build(base / "build", production) if build else None
  return root, built, limine, original, production


def bootctl_for(root, log=None):
  def bootctl(arguments, check):
    assert arguments[:2] == ["bootctl", "set-oneshot"] and check
    oneshot = root / stage.ONESHOT
    if log is not None:
      log.append(arguments[2])
    if arguments[2]:
      oneshot.write_bytes(efi_string(arguments[2]))
    else:
      oneshot.unlink()
  return bootctl


def advertise(root, receipt):
  (root / stage.ENTRIES).write_bytes(efi_strings((C.STOCK_ENTRY, receipt["entry_id"])))


def set_boot(root, selected, boot_id):
  (root / stage.SELECTED).write_bytes(efi_string(selected))
  (root / stage.BOOT_ID).write_text(boot_id + "\n")


